### ISSUE TITLE
`addGraphQLCustomFields ` tries to extend types (PaymentMethod) in wrong api-channels

### ISSUE THREAD

**Issue by Draykee** [vendure-ecommerce/vendure#1279]
**Describe the bug**
I've defined an enum called PaymentMethod for the shop-api (the PaymentMethod type usually only exists in admin-api - so there is no duplicate). Because of the custom fields generation for payment methods (which is new in 1.4) we get the following error:

```
error 9.12.21, 21:45 - [ExceptionHandler] Cannot extend non-object type "PaymentMethod".
Error: Cannot extend non-object type "PaymentMethod".
    at assertValidSDLExtension (...\node_modules\graphql\validation\validate.js:124:11)
    at Object.extendSchema (...\node_modules\graphql\utilities\extendSchema.js:77:43)
    at Object.addGraphQLCustomFields (...\node_modules\@vendure\core\src\api\config\graphql-custom-fields.ts:218:12)
    at buildSchemaForApi (...\node_modules\@vendure\core\src\api\config\configure-graphql-module.ts:145:18)
    at createGraphQLOptions (...\node_modules\@vendure\core\src\api\config\configure-graphql-module.ts:92:25)
```

It seams like the custom field graphql extension tries to extend the PaymentMethod type on the _wrong_ api channel

**To Reproduce**
1. Define an enum called PaymentMethod in the shop-api
2. Run the server

**Expected behavior**
The custom field graphql extension only tries to extend types that are known in the corresponding channel

**Environment (please complete the following information):**
 - @vendure/core version: 1.4-beta.0

**Possible workaround**
I just renamed my enum.

**Comment by dlhck** [comment]
This issue relates to a version of Vendure that is no longer supported. If the issue persists in the latest version, please open a new issue.
