### ISSUE TITLE
Vendure install, 1.4.3: ER_TABLE_EXISTS_ERROR: Table 'country_translation' already exists

### ISSUE THREAD

**Issue by agoransson** [vendure-ecommerce/vendure#1312]
**Describe the bug**
I upgraded from `1.2.1` to `1.4.3` today, and kept getting `QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'country_translation' already exists`.

I then went onto a brand new installation, `1.4.3`, and a brand new database (both MySQL and MariaDB tried).

**To Reproduce**
1. Create a docker container for database (MySQL or MariaDB)
2. Start a new project with 1.4.3 `yarn create @vendure api`
3. Follow instructions.

**Expected behavior**
I expected the install to work just like in 1.2.1, smooth and no problems.

**Environment (please complete the following information):**
 - @vendure/core version: `1.4.3`
 - Nodejs version: `v16.5.0`
 - Database (mysql/postgres etc): MySQL (5.7, 8.0, 8.0.27), and MariaDB (10.7.1), both running in fresh docker containers.

**Additional context**
This is the error generated (it tries 10 times, and gets the same SQL error on both MariaDB and MySQL).
```
  ✔ Installing dependencies
  ✔ Generating app scaffold
  ⠙ Initializing server
error 12/26/21, 4:19 PM - [TypeOrmModule] Unable to connect to the database. Retrying (9)...
QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'country_translation' already exists
    at QueryFailedError.TypeORMError [as constructor] (/Users/home/shop/api/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/Users/home/shop/api/src/error/QueryFailedError.ts:9:9)
    at Query.<anonymous> (/Users/home/shop/api/src/driver/mysql/MysqlQueryRunner.ts:183:37)
    at Query.<anonymous> (/Users/home/shop/api/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/home/shop/api/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/home/shop/api/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/home/shop/api/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/home/shop/api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/home/shop/api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/home/shop/api/node_modules/mysql/lib/protocol/Parser.js:43:10)
error 12/26/21, 4:19 PM - [ExceptionHandler] ER_TABLE_EXISTS_ERROR: Table 'country_translation' already exists
QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'country_translation' already exists
    at QueryFailedError.TypeORMError [as constructor] (/Users/home/shop/api/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/Users/home/shop/api/src/error/QueryFailedError.ts:9:9)
    at Query.<anonymous> (/Users/home/shop/api/src/driver/mysql/MysqlQueryRunner.ts:183:37)
    at Query.<anonymous> (/Users/home/shop/api/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Users/home/shop/api/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Users/home/shop/api/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Users/home/shop/api/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Users/home/shop/api/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/home/shop/api/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/home/shop/api/node_modules/mysql/lib/protocol/Parser.js:43:10)
error Command failed.
Exit code: 1
Command: /usr/local/bin/create
Arguments: api
Directory: /Users/home/shop
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by michaelbromley** [comment]
Hi, I just tried this with MariaDB v10.3, Node v16.13 and cannot reproduce:

```
Michael@XPS15 MINGW64 /c/Development/temp
$ yarn create @vendure test-1312
yarn create v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "@vendure/create@1.4.3" with binaries:
      - create
[#############################################################################################################] 190/190
Welcome to @vendure/create v1.4.3!

Let's configure a new Vendure project. First a few questions:

√ Which database are you using? » MariaDB
√ What's the database host address? ... localhost
√ What port is the database listening on? ... 3306
√ What's the name of the database? ... temp
√ What's the database user name? ... root
√ What's the database password? ...
√ Which programming language will you be using? » TypeScript
√ Populate with some sample product data? ... no / yes
√ What identifier do you want to use for the superadmin user? ... superadmin
√ What password do you want to use for the superadmin user? ... superadmin

Setting up your new Vendure project in C:\Development\temp\test-1312
This may take a few minutes...

  √ Installing dependencies
  √ Generating app scaffold
  - Initializing server
error 06/01/22, 16:58 - [Vendure Server] {"query":"INSERT INTO `search_index_item`(`languageCode`, `enabled`, `productNa
me`, `productVariantName`, `description`, `slug`, `sku`, `price`, `priceWithTax`, `facetIds`, `facetValueIds`, `collecti
onIds`, `collectionSlugs`, `channelIds`, `productPreview`, `productPreviewFocalPoint`, `productVariantPreview`, `product
VariantPreviewFocalPoint`, `inStock`, `productInStock`, `productVariantId`, `channelId`, `productId`, `productAssetId`,
`productVariantAssetId`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)","parameters
":["en",1,"Wooden Stool","Wooden Stool","Solid wood is a hardwearing natural material, which can be sanded and surface t

Success! Created a new Vendure server at C:\Development\temp\test-1312

We suggest that you start by typing:

    cd test-1312
    yarn start

Happy hacking!
Done in 315.48s.
```

The one error logged seems to be a race condition related to the search index - I think the app closes before the query is sent. But other than that it works, and running the server after installation works fine too.

I wonder what could be different in your environment? What OS are you using? I'm on Windows 10.

**Comment by agoransson** [comment]
Yes, for some reason I can't reproduce it either now... 

```
Andreass-MBP-2:temp agoransson$ yarn create @vendure test-1312
yarn create v1.22.11
warning package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "@vendure/create@1.4.3" with binaries:
      - create

Welcome to @vendure/create v1.4.3!

Let's configure a new Vendure project. First a few questions:

✔ Which database are you using? › MariaDB
✔ What's the database host address? … localhost
✔ What port is the database listening on? … 3333
✔ What's the name of the database? … temp
✔ What's the database user name? … root
✔ What's the database password? … ****
✔ Which programming language will you be using? › TypeScript
✔ Populate with some sample product data? … no / yes
✔ What identifier do you want to use for the superadmin user? … superadmin
✔ What password do you want to use for the superadmin user? … superadmin

Setting up your new Vendure project in /Users/agoransson/temp/test-1312
This may take a few minutes...

  ✔ Installing dependencies
  ✔ Installing dependencies
  ✔ Generating app scaffold
  ⠸ Initializing server
  ✔ Installing dependencies
  ✔ Generating app scaffold
  ⠼ Initializing server
  ✔ Installing dependencies
  ✔ Generating app scaffold
  ✔ Initializing server

Success! Created a new Vendure server at /Users/agoransson/temp/test-1312

We suggest that you start by typing:

    cd test-1312
    yarn start

Happy hacking!
✨  Done in 174.41s.
Andreass-MBP-2:temp agoransson$
```

I can't wrap my head around why it didn't work before.
