### ISSUE TITLE
Assign channels to an order

### ISSUE THREAD

**Issue by gkielwasser** [vendure-ecommerce/vendure#1391]
**Describe the bug**
Calling assignToChannels on an order throw hydrate exception
`this.channelService.assignToChannels(ctx, Order, order.id, orderChannels)`

**To Reproduce**
Call  `this.channelService.assignToChannels(ctx, Order, ...)`

**Expected behavior**
It should be possible to assign channels to an order

**Environment (please complete the following information):**
 - @vendure/core version:
 - Nodejs v14.17.6
 - Database: sqlite

**Additional context**
Stack trace
```
"message": "INTERNAL_SERVER_ERROR: The property \"discounts\" on the Order entity requires the Order.line
s relation to be joined.\nThis can be done with the EntityHydratorService: `await entityHydratorService.hydrate(ctx, ord
er, { relations: ['lines'] })`",
[run:server]   "variables": {}
[run:server] }
[run:server] Error: The property "discounts" on the Order entity requires the Order.lines relation to be joined.        
[run:server] This can be done with the EntityHydratorService: `await entityHydratorService.hydrate(ctx, order, { relatio
ns: ['lines'] })`
[run:server]     at Order.throwIfLinesNotJoined (\node_modules\@vendu
re\core\src\entity\order\order.entity.ts:325:19)
[run:server]     at Order.get discounts (\node_modules\@vendure\core\
src\entity\order\order.entity.ts:168:14)
[run:server]     at Order.get [as discounts] (\node_modules\@vendure\
core\src\entity\subscribers.ts:38:44)
[run:server]     at Function.assign (<anonymous>)
[run:server]     at \src\persistence\EntityPersistExecutor.ts:77:35
[run:server]     at Array.forEach (<anonymous>)
[run:server]     at EntityPersistExecutor.<anonymous> (\src\persistence\EntityPer
sistExecutor.ts:72:26)
[run:server]     at step (\node_modules\typeorm\node_modules\tslib\tslib.js:143:2
7)
```

**Comment by gkielwasser** [comment]
@michaelbromley Thanks, it works well !
