### ISSUE TITLE
Init a new vendure project doesn't work 

### ISSUE THREAD

**Issue by AyubTouba** [vendure-ecommerce/vendure#1456]
**Describe the bug**
After Init a new vendure project and try to run it, it gives database errors:

```
yarn run v1.22.15
yarn run v1.22.15
$ ts-node ./src/index-worker.ts
$ ts-node ./src/index.ts
[run:*server] info 3/4/22, 12:15 PM - [Vendure Server] Bootstrapping Vendure Server (pid: 217222)... 
[run:*worker] info 3/4/22, 12:15 PM - [Vendure Worker] Bootstrapping Vendure Worker (pid: 217215)... 
[run:*server] error 3/4/22, 12:15 PM - [TypeOrmModule] Unable to connect to the database. Retrying (1)...
[run:*server] QueryFailedError: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP FOREIGN KEY `FK_7256fef1bb42f1b38156b7449f5`; check that it exists
[run:*server]     at QueryFailedError.TypeORMError [as constructor] (/home/ayub/Documents/dev/lab/my-store/src/error/TypeORMError.ts:7:9)
[run:*server]     at new QueryFailedError (/home/ayub/Documents/dev/lab/my-store/src/error/QueryFailedError.ts:9:9)
[run:*server]     at Query.<anonymous> (/home/ayub/Documents/dev/lab/my-store/src/driver/mysql/MysqlQueryRunner.ts:183:37)
[run:*server]     at Query.<anonymous> (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/Connection.js:526:10)
[run:*server]     at Query._callback (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/Connection.js:488:16)
[run:*server]     at Query.Sequence.end (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
[run:*server]     at Query.ErrorPacket (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
[run:*server]     at Protocol._parsePacket (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/Protocol.js:291:23)
[run:*server]     at Parser._parsePacket (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/Parser.js:433:10)
[run:*server]     at Parser.write (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/Parser.js:43:10) 
[run:*server] error 3/4/22, 12:16 PM - [TypeOrmModule] Unable to connect to the database. Retrying (2)...
[run:*server] QueryFailedError: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP FOREIGN KEY `FK_7ee3306d7638aa85ca90d672198`; check that it exists
[run:*server]     at QueryFailedError.TypeORMError [as constructor] (/home/ayub/Documents/dev/lab/my-store/src/error/TypeORMError.ts:7:9)
[run:*server]     at new QueryFailedError (/home/ayub/Documents/dev/lab/my-store/src/error/QueryFailedError.ts:9:9)
[run:*server]     at Query.<anonymous> (/home/ayub/Documents/dev/lab/my-store/src/driver/mysql/MysqlQueryRunner.ts:183:37)
[run:*server]     at Query.<anonymous> (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/Connection.js:526:10)
[run:*server]     at Query._callback (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/Connection.js:488:16)
[run:*server]     at Query.Sequence.end (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
[run:*server]     at Query.ErrorPacket (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
[run:*server]     at Protocol._parsePacket (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/Protocol.js:291:23)
[run:*server]     at Parser._parsePacket (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/Parser.js:433:10)
[run:*server]     at Parser.write (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/Parser.js:43:10) 
[run:*worker] info 3/4/22, 12:17 PM - [Vendure Worker] Vendure Worker is ready 
[run:*worker] info 3/4/22, 12:17 PM - [JobQueue] Starting queue: apply-collection-filters 
[run:*worker] info 3/4/22, 12:17 PM - [JobQueue] Starting queue: send-email 
[run:*worker] info 3/4/22, 12:17 PM - [JobQueue] Starting queue: update-search-index 
[run:*server] error 3/4/22, 12:17 PM - [TypeOrmModule] Unable to connect to the database. Retrying (3)...
[run:*server] QueryFailedError: ER_CANT_CREATE_TABLE: Can't create table `mystore1`.`product_option_group` (errno: 121 "Duplicate key on write or update")
[run:*server]     at QueryFailedError.TypeORMError [as constructor] (/home/ayub/Documents/dev/lab/my-store/src/error/TypeORMError.ts:7:9)
[run:*server]     at new QueryFailedError (/home/ayub/Documents/dev/lab/my-store/src/error/QueryFailedError.ts:9:9)
[run:*server]     at Query.<anonymous> (/home/ayub/Documents/dev/lab/my-store/src/driver/mysql/MysqlQueryRunner.ts:183:37)
[run:*server]     at Query.<anonymous> (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/Connection.js:526:10)
[run:*server]     at Query._callback (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/Connection.js:488:16)
[run:*server]     at Query.Sequence.end (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
[run:*server]     at Query.ErrorPacket (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
[run:*server]     at Protocol._parsePacket (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/Protocol.js:291:23)
[run:*server]     at Parser._parsePacket (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/Parser.js:433:10)
[run:*server]     at Parser.write (/home/ayub/Documents/dev/lab/my-store/node_modules/mysql/lib/protocol/Parser.js:43:10)

```

**To Reproduce**
1. npm init @vendure my-store
2. finish the installation (I tried with populating data and without)
3. go to the project folder
4. execute npm run start

**Expected behavior**

**Environment (please complete the following information):**
 - v12.22.9
 - mysql

**Comment by deusama** [comment]
`Unable to connect to the database` seems like an obvious error to me, but that is not what you are asking for I guess?

**Comment by michaelbromley** [comment]
Does the database named in your vendure config file exist in mysql? Have you verified your connection details are correct?

**Comment by AyubTouba** [comment]
> Does the database named in your vendure config file exist in mysql? Have you verified your connection details are correct?
Yes, they're correct, the database has all the tables from npm init @vendure ...

**Comment by michaelbromley** [comment]
What version of mysql?

**Comment by AyubTouba** [comment]
I was choosing MySQL instead of MariaDB, no problems now,

Thank you
