### ISSUE TITLE
Getting Error While Creating Project

### ISSUE THREAD

**Issue by visahl8860** [vendure-ecommerce/vendure#1626]
I get this error

when creat app with MYSQL database, show this error

`Error: Could not connect to the database. Please check the connection settings in your Vendure config.`
`ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client`

![image](https://user-images.githubusercontent.com/88545007/173593366-bc8f0f4a-9fcd-4f4d-bc09-e1fc7301dec9.png)

`Error: Could not connect to the database. Please check the connection settings in your Vendure config.
[ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client]
    at throwConnectionError (C:\Users\BEAST\AppData\Local\npm-cache\_npx\fca31bc9a717a0f3\node_modules\@vendure\create\src\helpers.ts:345:11)
    at Handshake.<anonymous> (C:\Users\BEAST\AppData\Local\npm-cache\_npx\fca31bc9a717a0f3\node_modules\@vendure\create\src\helpers.ts:306:17)
    at Handshake.<anonymous> (F:\Project\Office\my-app\node_modules\mysql\lib\Connection.js:526:10)
    at Handshake._callback (F:\Project\Office\my-app\node_modules\mysql\lib\Connection.js:488:16)
    at Handshake.Sequence.end (F:\Project\Office\my-app\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Handshake.ErrorPacket (F:\Project\Office\my-app\node_modules\mysql\lib\protocol\sequences\Handshake.js:125:8)
    at Protocol._parsePacket (F:\Project\Office\my-app\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (F:\Project\Office\my-app\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (F:\Project\Office\my-app\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (F:\Project\Office\my-app\node_modules\mysql\lib\protocol\Protocol.js:38:16)`

when installing the app this error

node: v16.15.1
Server version: Mysql
npm: 8.12.1

**Comment by Draykee** [comment]
Did you try this?
https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

For me it looks like an configuration error with your MySQL database you want to use.

**Comment by szvest** [comment]
@Draykee The issue is not limited to MySQL. I am trying the latest 1.7 version with Postgres and getting the same error.
