### ISSUE TITLE
Images are not over ssl https

### ISSUE THREAD

**Issue by ashishkpaul** [vendure-ecommerce/vendure#1629]
**Describe the bug**

**To Reproduce**
1. Go to 'admin dashboard'
2. Click on 'assets'
On SSL certificate: Part of this page are not secured (such as images)

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 1.6
 - Nodejs version 12
 - Database (mysql/postgres etc): mariadb

**Additional context**
![ssl-images](https://user-images.githubusercontent.com/16308863/174062417-2219664d-42d7-4920-ad0e-b0ee9b6fb77b.png)

**Comment by ashishkpaul** [comment]
Okay, I resolved this by replacing trust porxy from false to true in a  file node_modules/@nestjs/platform-express/node_modules/express/lib/application.js 
`  // default settings
  this.enable('x-powered-by');
  this.set('etag', 'weak');
  this.set('env', env);
  this.set('query parser', 'extended');
  this.set('subdomain offset', 2);
  this.set('trust proxy', true);
`
Sir, Is it right to do so

**Comment by michaelbromley** [comment]
Hi,
I'd strongly advise against making changes to your node_modules directly - next time you install dependencies these changes will be lost.

It sounds to me like you might need to use the [assetUrlPrefix](https://www.vendure.io/docs/typescript-api/asset-server-plugin/asset-server-options/#asseturlprefix) option in your AssetServerPlugin to specify the correct url to your assets for production.

**Comment by ashishkpaul** [comment]
Hello sir, I am still struggling,  Its really very nice project but very hard to configure for non developers , I tried a lot and and also read the doc on [asseturlprefix](https://www.vendure.io/docs/typescript-api/asset-server-plugin/asset-server-options/#asseturlprefix) but didn't get.
as i understood i tried to replace 'string' by 'https://mydomain-name.com/assets/'  in a file /vendure-1.6.2/packages/asset-server-plugin/src/types.ts  but didn't get the result.  
`assetUrlPrefix?: string | ((ctx: RequestContext, identifier: string) => string);`

Sir, can you post with an example. Where we have to write complete URL prefix.

**Comment by ashishkpaul** [comment]
By doing 
`assetUrlPrefix?: "https://vendor.dingpack.com/assets/" | ((ctx: RequestContext, identifier: "https://vendor.dingpack.com/assets/") => "https://vendor.dingpack.com/assets/");`

It's giving the error

~/ecom/vendure-1.6.2/packages/dev-server$ yarn start
yarn run v1.22.19
$ concurrently yarn:run*
$ node -r ts-node/register index.ts
$ node -r ts-node/register index-worker.ts
[run:server] /home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:692
[run:server]     return new TSError(diagnosticText, diagnosticCodes);
[run:server]            ^
[run:server] TSError: ⨯ Unable to compile TypeScript:
[run:server] dev-config.ts(66,13): error TS2322: Type 'string' is not assignable to type '"assets"'.
[run:server] 
[run:server]     at createTSError (/home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:692:12)
[run:server]     at reportTSError (/home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:696:19)
[run:server]     at getOutput (/home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:883:36)
[run:server]     at Object.compile (/home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:1185:30)
[run:server]     at Module.m._compile (/home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:1309:30)
[run:server]     at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[run:server]     at Object.require.extensions.<computed> [as .ts] (/home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:1313:12)
[run:server]     at Module.load (internal/modules/cjs/loader.js:863:32)
[run:server]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[run:server]     at Module.require (internal/modules/cjs/loader.js:887:19) {
[run:server]   diagnosticText: `dev-config.ts(66,13): error TS2322: Type 'string' is not assignable to type '"assets"'.\n`,
[run:server]   diagnosticCodes: [ 2322 ]
[run:server] }
[run:worker] /home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:692
[run:worker]     return new TSError(diagnosticText, diagnosticCodes);
[run:worker]            ^
[run:worker] TSError: ⨯ Unable to compile TypeScript:
[run:worker] dev-config.ts(66,13): error TS2322: Type 'string' is not assignable to type '"assets"'.
[run:worker] 
[run:worker]     at createTSError (/home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:692:12)
[run:worker]     at reportTSError (/home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:696:19)
[run:worker]     at getOutput (/home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:883:36)
[run:worker]     at Object.compile (/home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:1185:30)
[run:worker]     at Module.m._compile (/home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:1309:30)
[run:worker]     at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[run:worker]     at Object.require.extensions.<computed> [as .ts] (/home/ashish/ecom/vendure-1.6.2/node_modules/ts-node/src/index.ts:1313:12)
[run:worker]     at Module.load (internal/modules/cjs/loader.js:863:32)
[run:worker]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[run:worker]     at Module.require (internal/modules/cjs/loader.js:887:19) {
[run:worker]   diagnosticText: `dev-config.ts(66,13): error TS2322: Type 'string' is not assignable to type '"assets"'.\n`,
[run:worker]   diagnosticCodes: [ 2322 ]
[run:worker] }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[run:server] yarn run run:server exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[run:worker] yarn run run:worker exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ashishkpaul** [comment]
Sir, Waiting for your suggestion

**Comment by michaelbromley** [comment]
Hi,

One thing to note:

> Its really very nice project but very hard to configure for non developers

Vendure is not really tageted at non-developers. That's why the documentation might be a little difficult - it assumes a certain level of knowledge of the underlying technologies and concepts.

In any case, here's an example:

```ts
AssetServerPlugin.init({
  // ... omitted existing config options for brevity
  assetUrlPrefix: 'https://mydomain-name.com/assets/',
});
```

This config will prepend all assets with the string `"https://mydomain-name.com/assets/"`.

**Comment by ashishkpaul** [comment]
I done sir, I am really thankful to you.
