### ISSUE TITLE
Email Handlers giving error

### ISSUE THREAD

**Issue by anmol1905** [vendure-ecommerce/vendure#1643]
**Describe the bug**
When I am changing devmode for production and adding SMTP details, and then when there is an order confirmation I get this error 
" 
```
TypeError: Cannot read properties of undefined (reading 'protocol')
0|server  |     at ctx (/var/www/x-Ecommerce/my-app/node_modules/@vendure/asset-server-plugin/src/common.ts:10:24)
0|server  |     at LocalAssetStorageStrategy.toAbsoluteUrlFn (/var/www/x-Ecommerce/my-app/node_modules/@vendure/asset-server-plugin/src/default-asset-storage-strategy-factory.ts:17:24)
0|server  |     at transformOrderLineAssetUrls (/var/www/x-Ecommerce/my-app/node_modules/@vendure/email-plugin/src/default-email-handlers.ts:104:46)
0|server  |     at EmailEventHandlerWithAsyncData._loadDataFn (/var/www/x-Ecommerce/my-app/node_modules/@vendure/email-plugin/src/default-email-handlers.ts:34:9)
0|server  |     at EmailEventHandlerWithAsyncData.handle (/var/www/x-Ecommerce/my-app/node_modules/@vendure/email-plugin/src/event-handler.ts:248:77)
0|server  |     at EmailPlugin.handleEvent (/var/www/x-Ecommerce/my-app/node_modules/@vendure/email-plugin/src/plugin.ts:241:42)
0|server  |     at SafeSubscriber._next (/var/www/x-Ecommerce/my-app/node_modules/@vendure/email-plugin/src/plugin.ts:228:29)
0|server  |     at SafeSubscriber.__tryOrUnsub (/var/wwwx-Ecommerce/my-app/node_modules/rxjs/src/internal/Subscriber.ts:265:10)
0|server  |     at SafeSubscriber.next (/var/www/x-Ecommerce/my-app/node_modules/rxjs/src/internal/Subscriber.ts:207:14)
0|server  |     at Subscriber._next (/var/www/x-Ecommerce/my-app/node_modules/rxjs/src/internal/Subscriber.ts:139:22)
```
"
**To Reproduce**
```
EmailPlugin.init({
            handlers: defaultEmailHandlers,
            templatePath: path.join(__dirname, '../static/email/templates'),
            transport: {
              type: 'smtp',
              host: 'smtpout.secureserver.net',
              port: 587,
              auth: {
                user: 'xxx',
                pass: 'xxx',
              },
              logging: true,
              debug: true,
            },
          }),

```

**Additional context**
when I test my SMTP credentials on some nodemailer basic example projects then it sends the email with no problem

**Comment by michaelbromley** [comment]
Hi,

thanks for the report. From the stack trace it appears that the `OrderStateTransitionEvent` which triggers the email does not have a request object attached to its `ctx` (RequestContext).

What payment method are you using on the order when this error occurs?

**Comment by anmol1905** [comment]
Hi Sir, any updates on this?
