### ISSUE TITLE
Order.get discounts error after PaymentSettled on 1.7.2~1.7.3

### ISSUE THREAD

**Issue by roytan883** [vendure-ecommerce/vendure#1801]
**Describe the bug**
after pay, got those error on console:
```
LogHandler-error: InternalServerError: The property "discounts" on the Order entity requires the Order.lines relation to be joined.
This can be done with the EntityHydratorService: `await entityHydratorService.hydrate(ctx, order, { relations: ['lines'] })`
at Order.throwIfLinesNotJoined (node_modules/@vendure/core/dist/entity/order/order.entity.js:143:19)
at Order.get discounts (node_modules/@vendure/core/dist/entity/order/order.entity.js:47:14)
at Order.get [as discounts] (node_modules/@vendure/core/dist/entity/subscribers.js:35:44)
```

**To Reproduce**
1. buy item
2. pay
3. order state chagne to `PaymentSettled`

**Expected behavior**
no error

**Environment (please complete the following information):**
 - @vendure/core version: 1.7.2, 1.7.3
 - Nodejs version
 - Database (mysql/postgres etc):postgres 14

**Comment by roytan883** [comment]
I got reason: `let ret = OrderService.settlePayment(ctx, paymentId)` , the `ret` can't be `JSON.stringify` to logger.

**Comment by roytan883** [comment]
I got reason: let ret = OrderService.settlePayment(ctx, paymentId) , the ret can't be JSON.stringify to logger.
