### ISSUE TITLE
Outdated sql.js dependency in Testing package causes ERR_INVALID_URL

### ISSUE THREAD

**Issue by melanki** [vendure-ecommerce/vendure#2054]
**Describe the bug**
I expect to clone the plugin template and run it 'as is'
But currently I get the following error due to outdated sql.js peer dependency in Vendure/Testing

```bash
TypeError: Failed to parse URL from /Users/user/Documents/Development/Repos/plugin-template-test/node_modules/sql.js/dist/sql-wasm.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at new URL (node:internal/url:588:13)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:234:25)
      at /Users/user/Documents/Development/Repos/plugin-template-test/node_modules/sql.js/dist/sql-wasm.js:165:139
      at /Users/user/Documents/Development/Repos/plugin-template-test/node_modules/sql.js/dist/sql-wasm.js:165:361
      at /Users/user/Documents/Development/Repos/plugin-template-test/node_modules/sql.js/dist/sql-wasm.js:165:374
      at new Promise (<anonymous>) {
    input: '/Users/user/Documents/Development/Repos/plugin-template-test/node_modules/sql.js/dist/sql-wasm.wasm',
    code: 'ERR_INVALID_URL'
  }
}
```

**To Reproduce**
1. Clone Vendure plugin template
2. Install dependencies using yarn
3. Try to run dev server using yarn start

**Expected behavior**
A running development server

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.3
 - Nodejs version: 18.4.2
 - Database (mysql/postgres etc): sql.js

**Additional context**
Upgrading sql.js to 1.8.0 solves this issue.

**Comment by tianyingchun** [comment]
With same issue, just upgraded to 1.8 and waiting vendure 2.0 I guess 😀
