### ISSUE TITLE
V2 [Admin UI compilation] 500 error on page refresh/direct route navigation

### ISSUE THREAD

**Issue by seminarian** [vendure-ecommerce/vendure#2168]
**Describe the bug**
When using `compile-admin-ui.ts` for pre-compiling the Admin UI (with or without extensions) and then starting the server with `yarn start` and navigating to a route that is not `/admin`, e.g. `/admin/catalog/collections`, and hitting the refresh button a 500 error is returned:
`{"statusCode":500,"message":"","timestamp":"2023-05-06T20:11:16.644Z","path":"/admin/catalog/collections"}`
![image](https://user-images.githubusercontent.com/9881519/236644936-97ee2e51-64ac-40f2-a90f-142a874f55cd.png)

**To Reproduce**
1. Add `compile-admin-ui.ts` 
```
import { compileUiExtensions } from '@vendure/ui-devkit/compiler';
import * as path from 'path';

void compileUiExtensions({
  outputPath: path.join(__dirname, '../__admin-ui'),
  extensions: [],
})
  .compile?.()
  .then(() => {
    process.exit(0);
  });
```
2. Run `yarn ts-node src/compile-admin-ui.ts`
3. And in `vendure-config.ts` add a reference to the pre-compiled version.
```
      app: {
        path: '__admin-ui/dist',
      },
```
4. Run `yarn build`
5. Run `yarn start`
6. Go to `http://localhost:3000/admin/catalog/collections` and see 500 error.
7. The Vendure server returns following error:
```
[server] error 5/6/23, 8:11 PM - [Vendure Server] path must be absolute or specify root to res.sendFile
[server] TypeError: path must be absolute or specify root to res.sendFile
[server]     at ServerResponse.sendFile (/home/pieter/projects/ecommerce-engine/node_modules/express/lib/response.js:441:11)
[server]     at /home/pieter/projects/ecommerce-engine/node_modules/@vendure/admin-ui-plugin/lib/src/plugin.js:139:17
[server]     at Layer.handle [as handle_request] (/home/pieter/projects/ecommerce-engine/node_modules/express/lib/router/layer.js:95:5)
[server]     at trim_prefix (/home/pieter/projects/ecommerce-engine/node_modules/express/lib/router/index.js:328:13)
[server]     at /home/pieter/projects/ecommerce-engine/node_modules/express/lib/router/index.js:286:9
[server]     at Function.process_params (/home/pieter/projects/ecommerce-engine/node_modules/express/lib/router/index.js:346:12)
[server]     at next (/home/pieter/projects/ecommerce-engine/node_modules/express/lib/router/index.js:280:10)
[server]     at SendStream.error (/home/pieter/projects/ecommerce-engine/node_modules/serve-static/index.js:121:7)
[server]     at SendStream.emit (node:events:513:28)
[server]     at SendStream.error (/home/pieter/projects/ecommerce-engine/node_modules/send/index.js:270:17) 
```

**Expected behavior**
Ability to navigate straight to routes or refreshing the routes.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.0-beta.2
 - Nodejs version: v16.19.0
 - Database (mysql/postgres etc): postgres

**Comment by seminarian** [comment]
Changing to this worked:
```
{
            path: path.join(__dirname, '../../__admin-ui/dist'),
          }
```
