### ISSUE TITLE
Example with secure mysql fails.

### ISSUE THREAD

**Issue by msj121** [vendure-ecommerce/vendure#2234]
I have mysql (Ver 8.0.33-0ubuntu0.23.04.2 for Linux on x86_64 ((Ubuntu)))

I added a user, password, blocked incoming calls except on my port 5231

ufw status:
`5231                       ALLOW       *.*.*.* ` (* just to protect data).

I can also connect mysql from my computer so I know settings are working (I allow my own computer as well).

However when I run current command:
`npx @vendure/create vendure-vendure`

it fails with error:
```
Error: Could not connect to the database. Please check the connection settings in your Vendure config.
[ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client]
    at throwConnectionError (/root/.npm/_npx/fca31bc9a717a0f3/node_modules/@vendure/create/src/helpers.ts:365:11)
    at Handshake.<anonymous> (/root/.npm/_npx/fca31bc9a717a0f3/node_modules/@vendure/create/src/helpers.ts:314:17)
    at Handshake.<anonymous> (/root/vendure-vendure/node_modules/mysql/lib/Connection.js:526:10)
    at Handshake._callback (/root/vendure-vendure/node_modules/mysql/lib/Connection.js:488:16)
    at Handshake.Sequence.end (/root/vendure-vendure/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Handshake.ErrorPacket (/root/vendure-vendure/node_modules/mysql/lib/protocol/sequences/Handshake.js:125:8)
    at Protocol._parsePacket (/root/vendure-vendure/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/root/vendure-vendure/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/root/vendure-vendure/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/root/vendure-vendure/node_modules/mysql/lib/protocol/Protocol.js:38:16)
```

Not sure what the issue is. Yes, I change the ip and port to match, and user and password.... Like I said same config on mysql workbench seems to work.

Also on this machine running vendure, I can connect with the standard mysql command giving it the same host,port,user,password, and database properties.... So security shouldn't be the issue?

**Comment by michaelbromley** [comment]
Hi,

This looks like the issue discussed here: https://stackoverflow.com/a/56509065/772859

That answer gives a work-around that might be acceptable to you. Long term it looks like we maybe want should ship with the `mysql2` client library instead on `mysql`: https://github.com/sidorares/node-mysql2

**Comment by msj121** [comment]
Oh thanks! Is there a suggested or preferred database? I was going to go with sqlite, but just assumed I wouldn't be able to use horizontal scaling... I don't have even a medium store and maybe I am over thinking this and just go with sqllite. Unless there is a suggested approach? Like Postgres, or mysql with local connection?

Thanks!

**Comment by msj121** [comment]
I have now installed mariadb on a local machine and faced similar issues... 

```
error 6/19/23, 12:11 AM - [TypeOrmModule] Unable to connect to the database. Retrying (2)...
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'dbadmin1'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (/root/vendure/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/root/vendure/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/root/vendure/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/root/vendure/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/root/vendure/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/root/vendure/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/root/vendure/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/root/vendure/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)

```

**Comment by msj121** [comment]
I have changed a few things for the MariaDB approach, like before it is localhost, but I changed the password to be longer without symbols, perhaps that was an issue. Similarly I was using 127.0.0.1 instead of localhost. Perhaps one of these was the issue, not sure, but I can close this now. Thanks.
