### ISSUE TITLE
Facets Across Channels - Primary key violation error on update Product

### ISSUE THREAD

**Issue by cboothe** [vendure-ecommerce/vendure#2268]
**Describe the bug**
I have always had issues trying to reuse facets across channels. I thought this might be fixed for version 2.

The issue is with the slug names being the same but for different channels causes a unique key constraint error.

Even with unique Facet Name the facet values are reused and causes the same issue.

**To Reproduce**
1. From a fresh install of v2.0.2
2. Click on Default Channel
3. Create a new channel "Channel 1", "Channel 2"
4. Switch back to Default Channel
5. Add a new Facet called "Application" Slug "application" Add some values: "HVAC", "Marine"
6. Switch to Channel 1 and click on Inventory
7. Add a product and under the right side click "Add Facet", search for "HVAC" and added it. Try to save the product by clicking on Update and you get the error.
8. Switch to Channel 2 and click on Inventory
9. Add a product and under the right side click "Add Facet", search for "HVAC" and added it. Try to save the product by clicking on Update and you get the error of duplicated keys.

**Expected behavior**
I expected to be able to reuse facets across channels. Meaning create global facets and values under the default channel.
Then switch to a channel and use a facet in either Channel 1 or Channel on a product. Example: Adding Application = HVAC to products in both Channel 1 and Channel 2.

**Environment (please complete the following information):**
 - @vendure/core version: v2.0.2
 - Nodejs version: v16.20.1
 - Database (mysql/postgres etc): postgres

**Comment by cboothe** [comment]
Happy to provide my Test database if it helps.

Here is the error message in the Vendure Server logs

`error 7/5/23, 8:49 AM - [Vendure Server] duplicate key value violates unique constraint "PK_1ab69c9935c61f7c70791ae0a9f"
QueryFailedError: duplicate key value violates unique constraint "PK_1ab69c9935c61f7c70791ae0a9f"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async SubjectExecutor.executeInsertOperations (/usr/src/app/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
    at async SubjectExecutor.execute (/usr/src/app/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
    at async EntityPersistExecutor.execute (/usr/src/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
    at async ProductVariantService.updateSingle (/usr/src/app/node_modules/@vendure/core/dist/service/services/product-variant.service.js:391:32)
    at async ProductVariantService.update (/usr/src/app/node_modules/@vendure/core/dist/service/services/product-variant.service.js:316:13)
error 7/5/23, 3:03 PM - [Vendure Server] duplicate key value violates unique constraint "PK_bebc9158e480b949565b4dc7a82"
QueryFailedError: duplicate key value violates unique constraint "PK_bebc9158e480b949565b4dc7a82"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async SubjectExecutor.executeInsertOperations (/usr/src/app/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
    at async SubjectExecutor.execute (/usr/src/app/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
    at async EntityPersistExecutor.execute (/usr/src/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
    at async ProductService.update (/usr/src/app/node_modules/@vendure/core/dist/service/services/product.service.js:199:32)
    at async ProductResolver.updateProduct (/usr/src/app/node_modules/@vendure/core/dist/api/resolvers/admin/product.resolver.js:68:16)`

**Comment by cboothe** [comment]
@michaelbromley Do you need the primary key definition to troubleshoot this?

**Comment by michaelbromley** [comment]
Investigation into this issue revealed that it is not related to the assignment of facet values and nor channels, but is some kind of data corruption in the user's database, which is throwing the error on _any_ update to the product.
