### ISSUE TITLE
can not connect to database

### ISSUE THREAD

**Issue by Narcissus313** [vendure-ecommerce/vendure#2292]
i have run mysql on docker and i made a database named 'vendure', then i applied this code. but it can not connect to the database. what is the problem?

`npx @vendure/create@latest reza-shop
  
┌  Let's create a Vendure App ✨ v2.0.4
│
◇  Which database are you using?
│  MySQL
│
◇  What's the database host address?
│  localhost
│
◇  What port is the database listening on?
│  3306
│
◇  What's the name of the database?
│  vendure
│
◇  What's the database user name?
│  root
│
◇  What's the database password?
│  reza12
│
◇  What identifier do you want to use for the superadmin user?
│  superadmin
│
◇  What password do you want to use for the superadmin user?
│  superadmin
│
◇  Populate with some sample product data?
│  yes
│
│
◇  Created package.json
│
◇  Successfully installed 7 dependencies
│
◇  Successfully installed 2 dev dependencies
│
◇  Generated app scaffold
│
◑  Initializing your new Vendure server   
Error: Could not connect to the database. Please check the connection settings in your Vendure config.
[ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client]
    at throwConnectionError (C:\Users\Reza\AppData\Local\npm-cache\_npx\b7017ac849fcdd84\node_modules\@vendure\create\src\helpers.ts:365:11)
    at Handshake.<anonymous> (C:\Users\Reza\AppData\Local\npm-cache\_npx\b7017ac849fcdd84\node_modules\@vendure\create\src\helpers.ts:314:17)
    at Handshake.<anonymous> (C:\Users\Reza\Desktop\vendure-master\reza-shop\node_modules\mysql\lib\Connection.js:526:10)
    at Handshake._callback (C:\Users\Reza\Desktop\vendure-master\reza-shop\node_modules\mysql\lib\Connection.js:488:16)
    at Handshake.Sequence.end (C:\Users\Reza\Desktop\vendure-master\reza-shop\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Handshake.ErrorPacket (C:\Users\Reza\Desktop\vendure-master\reza-shop\node_modules\mysql\lib\protocol\sequences\Handshake.js:125:8)
    at Protocol._parsePacket (C:\Users\Reza\Desktop\vendure-master\reza-shop\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Reza\Desktop\vendure-master\reza-shop\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Reza\Desktop\vendure-master\reza-shop\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Reza\Desktop\vendure-master\reza-shop\node_modules\mysql\lib\protocol\Protocol.js:38:16)`

**Comment by asonnleitner** [comment]
Which image and tag did you use to run your MySQL? Did you use a compose yaml file or a plain `docker run` command? If you used Docker Compose, could you please share your configuration? Alternatively, if you used `docker run`, could you please share the exact command you used to start your database?

**Comment by Narcissus313** [comment]
problem solved. first in docker, in mysql terminal tab i wrote:
`mysql -u root -p -h localhost`

then:
`ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'somePassword';`

then:
`CREATE DATABASE vendure;`

and then in the cli:
`npx @vendure/create@latest my-app`

the problem is gone!
