### ISSUE TITLE
Vendure Server didn't start after registering an account on the storefront with the superadmin email address.

### ISSUE THREAD

**Issue by ashishkpaul** [vendure-ecommerce/vendure#2388]
Hello team, the server has crashed after creating an account through the storefront with the same email address as the Vendure server admin's email ID.The output log is
```yarn run v1.22.19
$ concurrently yarn:start:*
$ node ./dist/index.js
$ node ./dist/index-worker.js
[worker] info 9/11/23, 4:51 PM - [Vendure Worker] Bootstrapping Vendure Worker (pid: 94602)... 
[worker] QueryFailedError: duplicate key value violates unique constraint "UQ_154f5c538b1576ccc277b1ed631"
[worker]     at PostgresQueryRunner.query (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
[worker]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[worker]     at async InsertQueryBuilder.execute (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
[worker]     at async SubjectExecutor.executeInsertOperations (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
[worker]     at async SubjectExecutor.execute (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
[worker]     at async EntityPersistExecutor.execute (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
[worker]     at async AdministratorService.ensureSuperAdminExists (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/@vendure/core/dist/service/services/administrator.service.js:292:46)
[worker]     at async AdministratorService.initAdministrators (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/@vendure/core/dist/service/services/administrator.service.js:55:9)
[worker]     at async InitializerService.onModuleInit (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/@vendure/core/dist/service/initializer.service.js:59:9)
[worker]     at async Promise.all (index 1) {
[worker]   query: 'INSERT INTO "public"."administrator"("createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "emailAddress", "userId") VALUES (DEFAULT, DEFAULT, DEFAULT, $1, $2, $3, DEFAULT) RETURNING "createdAt", "updatedAt", "id"',
[worker]   parameters: [ 'Super', 'Admin', 'superadmin@account.com' ],
[worker]   driverError: error: duplicate key value violates unique constraint "UQ_154f5c538b1576ccc277b1ed631"
[worker]       at /home/ubuntu/vendure/core/ecom-saa9vi/node_modules/pg/lib/client.js:526:17
[worker]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[worker]       at async PostgresQueryRunner.query (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25)
[worker]       at async InsertQueryBuilder.execute (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
[worker]       at async SubjectExecutor.executeInsertOperations (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
[worker]       at async SubjectExecutor.execute (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
[worker]       at async EntityPersistExecutor.execute (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
[worker]       at async AdministratorService.ensureSuperAdminExists (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/@vendure/core/dist/service/services/administrator.service.js:292:46)
[worker]       at async AdministratorService.initAdministrators (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/@vendure/core/dist/service/services/administrator.service.js:55:9)
[worker]       at async InitializerService.onModuleInit (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/@vendure/core/dist/service/initializer.service.js:59:9) {
[worker]     length: 261,
[worker]     severity: 'ERROR',
[worker]     code: '23505',
[worker]     detail: 'Key ("emailAddress")=(superadmin@account.com) already exists.',
[worker]     hint: undefined,
[worker]     position: undefined,
[worker]     internalPosition: undefined,
[worker]     internalQuery: undefined,
[worker]     where: undefined,
[worker]     schema: 'public',
[worker]     table: 'administrator',
[worker]     column: undefined,
[worker]     dataType: undefined,
[worker]     constraint: 'UQ_154f5c538b1576ccc277b1ed631',
[worker]     file: 'nbtinsert.c',
[worker]     line: '663',
[worker]     routine: '_bt_check_unique'
[worker]   },
[worker]   length: 261,
[worker]   severity: 'ERROR',
[worker]   code: '23505',
[worker]   detail: 'Key ("emailAddress")=(superadmin@account.com) already exists.',
[worker]   hint: undefined,
[worker]   position: undefined,
[worker]   internalPosition: undefined,
[worker]   internalQuery: undefined,
[worker]   where: undefined,
[worker]   schema: 'public',
[worker]   table: 'administrator',
[worker]   column: undefined,
[worker]   dataType: undefined,
[worker]   constraint: 'UQ_154f5c538b1576ccc277b1ed631',
[worker]   file: 'nbtinsert.c',
[worker]   line: '663',
[worker]   routine: '_bt_check_unique'
[worker] }
[server] info 9/11/23, 4:51 PM - [Vendure Server] Bootstrapping Vendure Server (pid: 94603)... 
[server] info 9/11/23, 4:51 PM - [AdminUiPlugin] Creating admin ui middleware (prod mode) 
[server] info 9/11/23, 4:51 PM - [AssetServerPlugin] Creating asset server middleware 
[server] info 9/11/23, 4:51 PM - [RoutesResolver] HealthController {/health}: 
[server] info 9/11/23, 4:51 PM - [RouterExplorer] Mapped {/health, GET} route 
[server] info 9/11/23, 4:51 PM - [RoutesResolver] StripeController {/payments}: 
[server] info 9/11/23, 4:51 PM - [RouterExplorer] Mapped {/payments/stripe, POST} route 
[server] QueryFailedError: duplicate key value violates unique constraint "UQ_154f5c538b1576ccc277b1ed631"
[server]     at PostgresQueryRunner.query (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
[server]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[server]     at async InsertQueryBuilder.execute (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
[server]     at async SubjectExecutor.executeInsertOperations (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
[server]     at async SubjectExecutor.execute (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
[server]     at async EntityPersistExecutor.execute (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
[server]     at async AdministratorService.ensureSuperAdminExists (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/@vendure/core/dist/service/services/administrator.service.js:292:46)
[server]     at async AdministratorService.initAdministrators (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/@vendure/core/dist/service/services/administrator.service.js:55:9)
[server]     at async InitializerService.onModuleInit (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/@vendure/core/dist/service/initializer.service.js:59:9)
[server]     at async Promise.all (index 1) {
[server]   query: 'INSERT INTO "public"."administrator"("createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "emailAddress", "userId") VALUES (DEFAULT, DEFAULT, DEFAULT, $1, $2, $3, DEFAULT) RETURNING "createdAt", "updatedAt", "id"',
[server]   parameters: [ 'Super', 'Admin', 'superadmin@account.com' ],
[server]   driverError: error: duplicate key value violates unique constraint "UQ_154f5c538b1576ccc277b1ed631"
[server]       at /home/ubuntu/vendure/core/ecom-saa9vi/node_modules/pg/lib/client.js:526:17
[server]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
[server]       at async PostgresQueryRunner.query (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:178:25)
[server]       at async InsertQueryBuilder.execute (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
[server]       at async SubjectExecutor.executeInsertOperations (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
[server]       at async SubjectExecutor.execute (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
[server]       at async EntityPersistExecutor.execute (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/typeorm/persistence/EntityPersistExecutor.js:148:21)
[server]       at async AdministratorService.ensureSuperAdminExists (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/@vendure/core/dist/service/services/administrator.service.js:292:46)
[server]       at async AdministratorService.initAdministrators (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/@vendure/core/dist/service/services/administrator.service.js:55:9)
[server]       at async InitializerService.onModuleInit (/home/ubuntu/vendure/core/ecom-saa9vi/node_modules/@vendure/core/dist/service/initializer.service.js:59:9) {
[server]     length: 261,
[server]     severity: 'ERROR',
[server]     code: '23505',
[server]     detail: 'Key ("emailAddress")=(superadmin@account.com) already exists.',
[server]     hint: undefined,
[server]     position: undefined,
[server]     internalPosition: undefined,
[server]     internalQuery: undefined,
[server]     where: undefined,
[server]     schema: 'public',
[server]     table: 'administrator',
[server]     column: undefined,
[server]     dataType: undefined,
[server]     constraint: 'UQ_154f5c538b1576ccc277b1ed631',
[server]     file: 'nbtinsert.c',
[server]     line: '663',
[server]     routine: '_bt_check_unique'
[server]   },
[server]   length: 261,
[server]   severity: 'ERROR',
[server]   code: '23505',
[server]   detail: 'Key ("emailAddress")=(superadmin@account.com) already exists.',
[server]   hint: undefined,
[server]   position: undefined,
[server]   internalPosition: undefined,
[server]   internalQuery: undefined,
[server]   where: undefined,
[server]   schema: 'public',
[server]   table: 'administrator',
[server]   column: undefined,
[server]   dataType: undefined,
[server]   constraint: 'UQ_154f5c538b1576ccc277b1ed631',
[server]   file: 'nbtinsert.c',
[server]   line: '663',
[server]   routine: '_bt_check_unique'
[server] }
[worker] yarn run start:worker exited with code 0
[server] yarn run start:server exited with code 0
Done in 15.20s.
```

**Comment by bulecampur** [comment]
What is the way out of this?

**Comment by fcFn** [comment]
@bulecampur The only way out for me to start the server was to go to the database and edit the entry with id `1` in the `administrator` table. I changed the email address of the administrator so that it's not `superadmin` and the server stopped crashing after that. However, I'm not sure what is causing that yet, so it might start again after a server restart. I suspected `synchronize` option in `vendure-config.ts`, but that ain't it.

It didn't crash after restarting the server after I had manually edited the superadmin user, so that's good.

This should probably be moved to Discussions?
