### ISSUE TITLE
Add UI for assigning Assets to Channels

### ISSUE THREAD

**Issue by DanielBiegler** [vendure-ecommerce/vendure#2478]
**Is your feature request related to a problem? Please describe.**
Was wondering why I can't see my images. Turns out, per the Docs (nice), Assets are Channel-Aware and need to be assigned.

I assumed you just select them and assign them via some button, but there is none:

![image](https://github.com/vendure-ecommerce/vendure/assets/14810858/aa340617-1da0-4f40-b4bd-18e9b02f4432)

Theres an argument to be had about automatically assigning assets when assigning products/variants to a new channel?

**Describe the solution you'd like**
For other props there are buttons:

![image](https://github.com/vendure-ecommerce/vendure/assets/14810858/9847855b-5bdd-4530-8004-b5164f73382d)

**Describe alternatives you've considered**
Alternative is programmatically assigning them manually via the api but thats the point - lets not have to do that :smile: 

```graphql
mutation assign {
  assignAssetsToChannel(
    input: {
      channelId: "3"
      assetIds: [
        "1"
      ]
    }
  ) {
    id
    name
  }
}
```

**Additional context**

Similar issue in regards to Assets and Channels: #2122

**Comment by michaelbromley** [comment]
Yes, I agree we should have a UI button to do this in the asset gallery, like the delete button.

> Theres an argument to be had about automatically assigning assets when assigning products/variants to a new channel?

This should be the case:

- [assignProductsToChannel](https://github.com/vendure-ecommerce/vendure/blob/b99d238ad35a0d2c843fb84d7f1b6441cd11d923/packages/core/src/service/services/product.service.ts#L319)
- [assignProductVariantsToChannel](https://github.com/vendure-ecommerce/vendure/blob/5e13b0e5132c31fb06274826c885815caa3c78e8/packages/core/src/service/services/product-variant.service.ts#L731]

But yes I see that similar logic has not been implemented for collections - thanks for pointing out that issue - I'll fix it.

**Comment by ezhil56x** [comment]
@michaelbromley

I tried setting up Vendure for local development and got the below errors. How can I fix this and make it ready for local development

During `DB=sqlite yarn populate` I'm getting the below error

```
EntityNotFoundError [GraphQLError]: error.entity-with-id-not-found
    at new I18nError (/home/ezhil/Desktop/vendure/packages/core/src/i18n/i18n-error.ts:25:9)
    at new EntityNotFoundError (/home/ezhil/Desktop/vendure/packages/core/src/common/error/errors.ts:97:9)
    at AdministratorService.assignRole (/home/ezhil/Desktop/vendure/packages/core/src/service/services/administrator.service.ts:243:19)
    at async AdministratorService.ensureSuperAdminExists (/home/ezhil/Desktop/vendure/packages/core/src/service/services/administrator.service.ts:323:13)
    at async AdministratorService.initAdministrators (/home/ezhil/Desktop/vendure/packages/core/src/service/services/administrator.service.ts:56:9)
    at async InitializerService.onModuleInit (/home/ezhil/Desktop/vendure/packages/core/src/service/initializer.service.ts:52:9)
    at async Promise.all (index 1)
    at async callModuleInitHook (/home/ezhil/Desktop/vendure/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
    at async NestApplication.callInitHook (/home/ezhil/Desktop/vendure/node_modules/@nestjs/core/nest-application-context.js:223:13)
    at async NestApplication.init (/home/ezhil/Desktop/vendure/node_modules/@nestjs/core/nest-application.js:100:9) {
  path: undefined,
  locations: undefined,
  extensions: { code: 'ENTITY_NOT_FOUND' },
  variables: { entityName: 'Role', id: 1 },
  code: 'ENTITY_NOT_FOUND',
  logLevel: 1
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And during `DB=sqlite yarn start` I'm getting the below error

```
[:server] verbose 1/13/24, 3:24 PM - [Vendure Server] FORBIDDEN: error.forbidden 
[:server] verbose 1/13/24, 3:24 PM - [Vendure Server] FORBIDDEN: error.forbidden 
[:server] verbose 1/13/24, 3:24 PM - [Vendure Server] FORBIDDEN: error.forbidden
```

**Comment by mrkirthi-24** [comment]
/attempt #2478 i am in the waitlist if @RutamBhagat is unassigned.

**Comment by michaelbromley** [comment]
@ezhil56x look like the issue was introduced with a recent commit. I'm investigating.

**Comment by dlhck** [comment]
This should be done together with #2903

**Comment by casperiv0** [comment]
> This should be done together with https://github.com/vendure-ecommerce/vendure/issues/2903

Does this mean, this feature will only be completed when #2903 is completed or could it be completed beforehand? In the latter case, I could look into this :)!

**Comment by dlhck** [comment]
@casperiv0 we are planning to do this task together with #2903 and release it with v3.2. If you can take a look before, even better. Maybe we can ship it with v3.1

**Comment by dlhck** [comment]
This will be included in the beta release of the new `@vendure/dashboard`. Maybe someone can contribute this to the legacy `@vendure/admin-ui`. @casperiv0 could you do that? Thank you!

**Comment by lucatk** [comment]
Will the solution for this include a way to have non channel-aware assets?
For some context, I need to have an asset custom field on channels (think "vendor logo" in a multi-vendor setup).
Confusingly, the set asset is only shown in the Admin UI if I am currently viewing the channel the asset was created in - in this instance, the default channel.
If I switch to another channel and want to view the assets that are set on channels, it is displayed as though there is no asset set.

<details><summary>Details</summary>
<p>

<img width="1054" alt="Image" src="https://github.com/user-attachments/assets/9060ba59-73dd-4293-a024-e30dadae5a15" />

<img width="1100" alt="Image" src="https://github.com/user-attachments/assets/c7d290e5-3d8e-4318-9bfa-5453f33e1ba7" />

</p>
</details>

**Comment by dlhck** [comment]
This feature request has been moved to GitHub Discussions for community voting.
Please upvote the discussion if you would like to see this implemented: https://github.com/vendurehq/vendure/discussions/4279
