### ISSUE TITLE
listQueryBuilder.build() throw `"Not unique table/alias:` error while upgrade to vendure `2.2.0-next.6`

### ISSUE THREAD

**Issue by tianyingchun** [vendure-ecommerce/vendure#2738]
**Describe the bug**
 While upgrade to vendure `2.2.0-next.6`, typeorm 0typeorm@0.3.20

it wll throw `"Not unique table/alias:` if we have `relation:['parent']`, and `parent` reference this entity self

**To Reproduce**
```ts
@Entity('lens_process_option')
export class LensProcessOption extends VendureEntity implements Translatable {
  constructor(input?: DeepPartial<LensProcessOption>) {
    super(input);
  }

  @ManyToOne(() => LensProcessOption, (type) => type.parent)
  parent: LensProcessOption | null;


  @Column('int', { nullable: true })
  parentId: ID | null;

``

while we have query as below:

```ts
 findAll(
    ctx: RequestContext,
    options?: ListQueryOptions<LensProcessOption>
  ): Promise<PaginatedList<Translated<LensProcessOption>>> {
    return this.listQueryBuilder
      .build(LensProcessOption, options, { relations: ['parent'], ctx })
      .getManyAndCount()
      .then(([processOptions, totalItems]) => {
        const items = processOptions.map((processOption) =>
          translateDeep(processOption, ctx.languageCode, ['parent'])
        );
        return {
          items,
          totalItems,
        };
      });
  }

```
it will throw error 

```
 code: 'ER_NONUNIQ_TABLE',
  errno: 1066,
  sqlState: '42000',
  sqlMessage: "Not unique table/alias: 'LensProcessOption'",
```

```sql


SELECT

	`LensProcessOption`.`parentId` AS `LensProcessOption_parentId`,
	`LensProcessOption`.`id` AS `LensProcessOption_id`,

	`LensProcessOption`.`createdAt` AS `LensProcessOption_createdAt`,
	`LensProcessOption`.`updatedAt` AS `LensProcessOption_updatedAt`,
	
	`LensProcessOption`.`parentId` AS `LensProcessOption_parentId`,
	`LensProcessOption`.`id` AS `LensProcessOption_id` 
FROM
	`lens_process_option` `LensProcessOption`
	LEFT JOIN `lens_process_option_translation` `LensProcessOption__translations` ON `LensProcessOption__translations`.`baseId` = `LensProcessOption`.`id`
	INNER JOIN `lens_process_option` `LensProcessOption` ON `LensProcessOption`.`parentId` = `LensProcessOption`.`id` 
WHERE
	`LensProcessOption`.`id` IN (

```

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 2.2.0-next-6
 - Nodejs version: 
 - Database (mysql/postgres etc):mysql

**Additional context**

**Comment by tianyingchun** [comment]
https://github.com/tianyingchun/vendure-issue

checkout banch `vendure_issue_2738`

1. yarn install
2. cd `dev-server`
3. yarn serve


```
  code: 'ER_NONUNIQ_TABLE',
  errno: 1066,
  sqlState: '42000',
  sqlMessage: "Not unique table/alias: 'Menu'",
  sql: ''
```
```sql
SELECT `Menu`.`createdAt` AS `Menu_createdAt`, `Menu`.`updatedAt` AS `Menu_updatedAt`, `Menu`.`code` AS `Menu_code`, `Menu`.`parentId` AS `Menu_parentId`, `Menu`.`id` AS `Menu_id`, `Menu`.`createdAt` AS `Menu_createdAt`, `Menu`.`updatedAt` AS `Menu_updatedAt`, `Menu`.`code` AS `Menu_code`, `Menu`.`parentId` AS `Menu_parentId`, `Menu`.`id` AS `Menu_id` FROM `menu` `Menu` INNER JOIN `menu` `Menu` ON `Menu`.`parentId` = `Menu`.`id` WHERE `Menu`.`id` IN (1, 2, 3)
```

**Comment by michaelbromley** [comment]
@monrostar is this the issue you ran into when updating TypeORM?

**Comment by monrostar** [comment]
Yes, it may be necessary to add a check not only for Tree but also if the relation decorator points to the same table.
I hadn't considered that such ties could be broken, too.

> @monrostar is this the issue you ran into when updating TypeORM?

**Comment by monrostar** [comment]
@michaelbromley I can do this fix today

**Comment by monrostar** [comment]
> ```ts
> 
>   @ManyToOne(() => LensProcessOption, (type) => type.parent)
>   parent: LensProcessOption | null;
> 
> 
>   @Column('int', { nullable: true })
>   parentId: ID | null;
> ```

A fix will be ready today. I found a cause

**Comment by tianyingchun** [comment]
also need to considered `translations`

**Comment by tianyingchun** [comment]
please see my latest updated repo https://github.com/tianyingchun/next-issue/tree/vendure_issue_2738
it will always throw 

```
InternalServerError [GraphQLError]: error.entity-has-no-translation-in-language
    at new I18nError (/Users/tianyingchun/Documents/coding/kzfoo/vendure-issue/node_modules/@vendure/core/dist/i18n/i18n-error.js:21:9)
    at new InternalServerError (/Users/tianyingchun/Documents/coding/kzfoo/vendure-issue/node_modules/@vendure/core/dist/common/error/errors.js:15:9)
    at translateEntity (/Users/tianyingchun/Documents/coding/kzfoo/vendure-issue/node_modules/@vendure/core/dist/service/helpers/utils/translate-entity.js:33:15)
    at translateLeaf (/Users/tianyingchun/Documents/coding/kzfoo/vendure-issue/node_modules/@vendure/core/dist/service/helpers/utils/translate-entity.js:104:20)
    at translateDeep (/Users/tianyingchun/Documents/coding/kzfoo/vendure-issue/node_modules/@vendure/core/dist/service/helpers/utils/translate-entity.js:89:21)
    at TranslatorService.translate (/Users/tianyingchun/Documents/coding/kzfoo/vendure-issue/node_modules/@vendure/core/dist/service/helpers/translator/translator.service.js:54:53)
    at file:///Users/tianyingchun/Documents/coding/kzfoo/vendure-issue/packages/plugin-issue/src/services/menu.service.ts:82:76
    at Array.map (<anonymous>)
    at file:///Users/tianyingchun/Documents/coding/kzfoo/vendure-issue/packages/plugin-issue/src/services/menu.service.ts:82:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  path: undefined,
  locations: undefined,
  extensions: { code: 'INTERNAL_SERVER_ERROR' },
  variables: { entityName: 'Menu', languageCode: ',,en' },
  code: 'INTERNAL_SERVER_ERROR',
  logLevel: 0
}
```

**Comment by tianyingchun** [comment]
because `parent` relation missed reload all `translations` eager

**Comment by monrostar** [comment]
The updated fix is ready

**Comment by tianyingchun** [comment]
it works with `minor` local build , thanks @monrostar  @michaelbromley
