### ISSUE TITLE
Asset server version caused installation problem on 2.2.x-beta

### ISSUE THREAD

**Issue by mschipperheyn** [vendure-ecommerce/vendure#2739]
**Describe the bug**
I got a very hard to resolve issue that I tracked down as related to the asset-server-plugin. After installing another plugin I suddenly couldn't start the system anymore with this error

```
yarn run v1.22.21
$ yarn workspace @maos/backend start
$ concurrently yarn:start:server & yarn start:worker
$ ts-node ./src/index-worker.ts
$ ts-node ./src/index.ts
/Users/mschipperheyn/workspace/maos/node_modules/sharp/lib/sharp.js:114
  throw new Error(help.join('\n'));
        ^
Error: Could not load the "sharp" module using the darwin-arm64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=darwin --cpu=arm64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Users/mschipperheyn/workspace/maos/node_modules/sharp/lib/sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .js] (/Users/mschipperheyn/workspace/maos/packages/backend/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/mschipperheyn/workspace/maos/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
[start:server] /Users/mschipperheyn/workspace/maos/node_modules/sharp/lib/sharp.js:114
[start:server]   throw new Error(help.join('\n'));
[start:server]         ^
[start:server] Error: Could not load the "sharp" module using the darwin-arm64 runtime
[start:server] Possible solutions:
[start:server] - Ensure optional dependencies can be installed:
[start:server]     npm install --include=optional sharp
[start:server]     yarn add sharp --ignore-engines
[start:server] - Ensure your package manager supports multi-platform installation:
[start:server]     See https://sharp.pixelplumbing.com/install#cross-platform
[start:server] - Add platform-specific dependencies:
[start:server]     npm install --os=darwin --cpu=arm64 sharp
[start:server] - Consult the installation documentation:
[start:server]     See https://sharp.pixelplumbing.com/install
[start:server]     at Object.<anonymous> (/Users/mschipperheyn/workspace/maos/node_modules/sharp/lib/sharp.js:114:9)
[start:server]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[start:server]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[start:server]     at Object.require.extensions.<computed> [as .js] (/Users/mschipperheyn/workspace/maos/packages/backend/node_modules/ts-node/src/index.ts:1608:43)
[start:server]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[start:server]     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
[start:server]     at Module.require (node:internal/modules/cjs/loader:1235:19)
[start:server]     at require (node:internal/modules/helpers:176:18)
[start:server]     at Object.<anonymous> (/Users/mschipperheyn/workspace/maos/node_modules/sharp/lib/constructor.js:10:1)
[start:server]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
```

The problem is caused by a number of `@img/sharp-darwin-arm64@0.33.2` style dependencies being included in `yarn.lock` for some reason. The reason seems to be (I can't be sure. It was kind of rabbit hole), the use of sharp@0.33.2 in the @vendure beta instead of sharp@0.33.5 in the current main. By adding a resolution of `"sharp": "^0.32.5"` in package.json, the problem went away.

**To Reproduce**
I'm not sure exactly if this is easily reproducible. I'm on yarn 1.22.21 and a resolved @vendure 2.2.0-beta.6 based on a ser @vendure-2.2.0-beta.5 and this started happening kinda out of the blue.

**Expected behavior**
sharp dependency should be at least at `main` level
@img should not be included in yarn.lock as a dependency

**Environment (please complete the following information):**
 - @vendure/core version: 2.2.0-beta.6
 - Nodejs version 20.x and 21.x
 - Database (mysql/postgres etc): postgres

**Additional context**
Macbook pro M3

**Comment by michaelbromley** [comment]
This is because Yarn v1.x does not support the optionalDependencies feature that the latest versions of Sharp use to distribute platform-specific binaries.

The solution is to move away from Yarn v1.x, which is completely unmaintained and has had no commits for the past 2 years.

**Comment by alexisvigoureux** [comment]
I'm having the same problem with version 2.2.0-beta.6. Is Vendure planning to migrate to yarn 3 or 4?

**Comment by michaelbromley** [comment]
I migrated the `minor` branch to use npm rather than yarn. Modern Yarn versions should also be fine too.

**Comment by michaeldev5** [comment]
Yarn v4 does not work with Vendure. Everything is broken.

**Comment by mschipperheyn** [comment]
A workaround for me seems to be to delete yarn.lock and reinstall. That seems to fix the issue each time.

**Comment by michaelbromley** [comment]
Closing in favour of:

- https://github.com/vendure-ecommerce/vendure/issues/2439
