### ISSUE TITLE
Error starting application in Docker container

### ISSUE THREAD

**Issue by JoezerG** [vendure-ecommerce/vendure#2777]
**Describe the issue**
The application in development mode works perfectly, when it is built (`npm run build && npm run start:server`) and executed it also works correctly, but when running it in a Docker container, the following error appears

```
2024-04-10 00:44:54 info 4/10/24, 5:44 AM - [Vendure Server] Bootstrapping Vendure Server (pid: 19)... 
2024-04-10 00:44:54 error 4/10/24, 5:44 AM - [ExceptionHandler] Received invalid input.
2024-04-10 00:44:54 TypeError: Received invalid input.
2024-04-10 00:44:54     at applySubschemaConfigTransforms (/usr/src/app/node_modules/@graphql-tools/stitch/cjs/stitchSchemas.js:102:15)
2024-04-10 00:44:54     at stitchSchemas (/usr/src/app/node_modules/@graphql-tools/stitch/cjs/stitchSchemas.js:16:50)
2024-04-10 00:44:54     at generateListOptions (/usr/src/app/node_modules/@vendure/core/dist/api/config/generate-list-options.js:67:39)
2024-04-10 00:44:54     at buildSchemaForApi (/usr/src/app/node_modules/@vendure/core/dist/api/config/configure-graphql-module.js:99:66)
2024-04-10 00:44:54     at async createGraphQLOptions (/usr/src/app/node_modules/@vendure/core/dist/api/config/configure-graphql-module.js:53:25)
2024-04-10 00:44:54     at async InstanceWrapper.useFactory [as metatype] (/usr/src/app/node_modules/@nestjs/graphql/dist/graphql.module.js:89:48)
2024-04-10 00:44:54     at async Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:369:37)
2024-04-10 00:44:54     at async callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:65:34)
2024-04-10 00:44:54     at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:144:24)
2024-04-10 00:44:54     at async Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:70:13) 
```

**Expected behavior**
Running normally

**I have already tried**

- Disabled all plugins
- Remove customFields
- Remove custom Admin Modules

**Attach my current configuration**

vendure-config.ts
```typescript
import {
  dummyPaymentHandler,
  DefaultJobQueuePlugin,
  DefaultSearchPlugin,
  VendureConfig,
  DefaultAssetNamingStrategy,
  manualFulfillmentHandler,
} from "@vendure/core";
import { defaultEmailHandlers, EmailPlugin } from "@vendure/email-plugin";
import {
  AssetServerPlugin,
  configureS3AssetStorage,
} from "@vendure/asset-server-plugin";
import { AdminUiPlugin } from "@vendure/admin-ui-plugin";
import "dotenv/config";
import path from "node:path";
import { ContentPlugin } from "./plugins/content/content-plugin";
import customFields from "./customfields";
import {
  OrderExportPlugin,
  DefaultExportStrategy,
} from "@pinelab/vendure-plugin-order-export";
import {
  AverageOrderValueMetric,
  MetricsPlugin,
  SalesPerProductMetric,
} from "@pinelab/vendure-plugin-metrics";
import { ServientregaPlugin } from "./plugins/shipping-methods/servientrega-plugin";
import { customAdminUi } from "./compile-admin-ui";

const IS_DEV = process.env.APP_ENV === "dev";
const IS_PROD = path.basename(__dirname) === "dist";

export const config: VendureConfig = {
  apiOptions: {
    port: 3000,
    adminApiPath: "admin-api",
    shopApiPath: "shop-api",
    // The following options are useful in development mode,
    // but are best turned off for production for security
    // reasons.
    ...(IS_DEV
      ? {
          adminApiPlayground: {
            settings: { "request.credentials": "include" } as any,
          },
          adminApiDebug: true,
          shopApiPlayground: {
            settings: { "request.credentials": "include" } as any,
          },
          shopApiDebug: true,
        }
      : {}),
  },
  authOptions: {
    tokenMethod: ["bearer", "cookie"],
    superadminCredentials: {
      identifier: process.env.SUPERADMIN_USERNAME,
      password: process.env.SUPERADMIN_PASSWORD,
    },
    cookieOptions: {
      secret: process.env.COOKIE_SECRET,
    },
  },
  dbConnectionOptions: {
    type: "mariadb",
    synchronize: true,
    migrations: [path.join(__dirname, "./migrations/*.+(js|ts)")],
    logging: false,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: +process.env.DB_PORT,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
  },
  paymentOptions: {
    paymentMethodHandlers: [dummyPaymentHandler],
  },
  shippingOptions: {
    fulfillmentHandlers: [manualFulfillmentHandler],
  },
  customFields,
  plugins: [
    AssetServerPlugin.init({
      route: "assets",
      assetUploadDir: path.join(__dirname, "..", "static", "assets"),
      presets: [],
      namingStrategy: new DefaultAssetNamingStrategy(),
      storageStrategyFactory: configureS3AssetStorage({
        bucket: "bucket",
        credentials: {
          accessKeyId: process.env.SPACES_KEY ?? "",
          secretAccessKey: process.env.SPACES_SECRET ?? "",
        },
        nativeS3Configuration: {
          endpoint: `${process.env.BUCKET_ENDPOINT}/${process.env.BUCKET_FOLDER}`,
          region: "auto",
        },
      }),
    }),
    DefaultJobQueuePlugin.init({ useDatabaseForBuffer: true }),
    DefaultSearchPlugin.init({ bufferUpdates: false, indexStockStatus: true }),
    EmailPlugin.init({
      handlers: defaultEmailHandlers,
      templatePath: path.join(__dirname, "..", "static/email/templates"),
      transport: {
        type: "smtp",
        host: "smtp.resend.com",
        port: 587,
        auth: {
          user: "resend",
          pass: process.env.RESEND_KEY,
        },
      },
    }),
    AdminUiPlugin.init({
      route: "admin",
      port: 3002,
      adminUiConfig: {
        brand: "STORE BELLA",
        hideVendureBranding: false,
        loginImageUrl: "LOGO URL",
        apiPort: 3000,
      },
      app: customAdminUi({ recompile: !IS_PROD, devMode: !IS_PROD }),
    }),
    OrderExportPlugin.init({ exportStrategies: [new DefaultExportStrategy()] }),
    MetricsPlugin.init({
      metrics: [new AverageOrderValueMetric(), new SalesPerProductMetric()],
    }),
    ServientregaPlugin,
    ContentPlugin,
  ],
};
```

customFields.ts
```typescript
import { CustomFields, LanguageCode } from "@vendure/core";

const customFields: CustomFields = {
  Collection: [
    {
      name: "colorCode",
      label: [
        { languageCode: LanguageCode.es, value: "Codigo de color" },
        { languageCode: LanguageCode.en, value: "Color Code" },
      ],
      type: "string",
      length: 6,
      nullable: true,
      ui: {
        component: "text-form-input",
        prefix: "#",
      },
    },
  ],
  Product: [
    {
      name: "selfLoveCaption",
      type: "string",
      nullable: true,
      label: [
        { languageCode: LanguageCode.es, value: "Self Love" },
        { languageCode: LanguageCode.en, value: "Self Love" },
      ],
      ui: {
        component: "textarea-form-input",
      },
    },
    {
      name: "usageCaption",
      type: "string",
      nullable: true,
      label: [
        { languageCode: LanguageCode.es, value: "Uso" },
        { languageCode: LanguageCode.en, value: "Usage" },
      ],
      ui: {
        component: "textarea-form-input",
      },
    },
  ],
  ProductVariant: [
    {
      name: "colorCode",
      label: [
        { languageCode: LanguageCode.es, value: "Codigo de color" },
        { languageCode: LanguageCode.en, value: "Color Code" },
      ],
      type: "string",
      length: 6,
      nullable: true,
      ui: {
        component: "text-form-input",
        prefix: "#",
      },
    },
  ],
};

export default customFields;
```

Dockerfile
```Dockerfile
FROM node:20 AS BUILD
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install --omit=dev
COPY . .
RUN npm run build
# RUN npm prune --production
```

**Comment by michaelbromley** [comment]
Hi,

that kind of error is often traced back to a dependency issue - usually multiple versions of the `graphql` package. Can you try also copying over your lockfile into the docker image?

```dockerfile
COPY package-lock.json ./
```

**Comment by sergey-chathouse** [comment]
I encountered the same issue after upgrading GraphQL to version 16.8.2 for all dependent packages, except for Vendure. I recommend that the Vendure team specifies the GraphQL dependency as "graphql": "^16.8.0" instead of an exact version. This will allow it to be updated alongside other packages.

Solution:
To resolve this, add the following to your package.json:

```
"overrides": {
  "graphql": "16.8.2"
}
```
This will ensure that the correct version of GraphQL is used across all dependencies.

**Comment by michaelbromley** [comment]
@sergey-chathouse we'll consider loosening the dependency in an upcoming version. The reason it is pinned is due to past issues where subtle changes between patch versions have caused issues.
