### ISSUE TITLE
collection-duplicator throws error on asset association

### ISSUE THREAD

**Issue by mschipperheyn** [vendure-ecommerce/vendure#2787]
**Describe the bug**
When using the collection-duplicator that has assets associated to it, an error is thrown because of an odd [constructor](https://github.com/vendure-ecommerce/vendure/blob/09f25d39bf8510cc0c13c19396589492565eaf34/packages/core/src/service/services/asset.service.ts#L614) reference.

The root cause seems to be that the when updating a collection, the asset service update collection function is called with an empty array. The sort function then assumes there is at least 1 item and references the first one, which can be undefined.

```
error 4/16/24, 5:05 PM - [Vendure Server] Cannot read properties of undefined (reading 'constructor')
TypeError: Cannot read properties of undefined (reading 'constructor')
    at AssetService.createOrderableAssets (/Users/mschipperheyn/workspace/maos/node_modules/@vendure/core/src/service/services/asset.service.ts:614:70)
    at AssetService.updateEntityAssets (/Users/mschipperheyn/workspace/maos/node_modules/@vendure/core/src/service/services/asset.service.ts:275:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CollectionService.create (/Users/mschipperheyn/workspace/maos/node_modules/@vendure/core/src/service/services/collection.service.ts:465:9)
    at async EntityDuplicator.duplicate [as duplicateFn] (/Users/mschipperheyn/workspace/maos/node_modules/@vendure/core/src/config/entity/entity-duplicators/collection-duplicator.ts:66:38)
    at async /Users/mschipperheyn/workspace/maos/node_modules/@vendure/core/src/service/helpers/entity-duplicator/entity-duplicator.service.ts:76:35
```

**To Reproduce**
1. Create a collection with associated assets
2. Duplicate the collection

**Expected behavior**
It should copy the collection and copy associated assets

**Environment (please complete the following information):**
 - @vendure/core version: 2.2.0
 - Nodejs version: 18.x
 - Database (mysql/postgres etc): postgres

**Comment by mschipperheyn** [comment]
After further investigation I found that the cause of this issue is that when I use the collection import through the populator on a non default channel, the assets get imported on the default channel. [Here](https://github.com/vendure-ecommerce/vendure/blob/9c1cb1662e899c62d93f8741f9476f415c721998/packages/core/src/service/services/asset.service.ts#L270), it will subsequently return an empty array and fail

It would seem that the assetImporter needs to ensure imported assets get assigned to the correct channel by adding ctx [here](https://github.com/vendure-ecommerce/vendure/blob/9c1cb1662e899c62d93f8741f9476f415c721998/packages/core/src/data-import/providers/populator/populator.ts#L128).
