### ISSUE TITLE
[EmailPlugin] Cannot read properties of undefined (reading 'headers') in production

### ISSUE THREAD

**Issue by casperiv0** [vendure-ecommerce/vendure#2872]
**Describe the bug**
When handling incoming orders from Mollie in production, we're getting the following error when we want to send a order success/confirmation email:

```
...
[MolliePlugin] Processing status 'paid' for order XXX for channel ...
[MolliePlugin] Payment for order GKHH3SWCTSZSSB2A with amount XXX created with state 'Settled'
error 5/31/24, 5:14 AM - [EmailPlugin] Cannot read properties of undefined (reading 'headers')
TypeError: Cannot read properties of undefined (reading 'headers')
  at ctx (/usr/src/app/node_modules/@vendure/asset-server-plugin/lib/src/common.js:10:44)
  at S3AssetStorageStrategy.toAbsoluteUrlFn [as toAbsoluteUrl] (/usr/src/app/node_modules/@vendure/asset-server-plugin/lib/src/s3-asset-storage-strategy.js:116:28)
  at transformOrderLineAssetUrls (/usr/src/app/node_modules/@vendure/email-plugin/lib/src/handler/default-email-handlers.js:78:46)
  at EmailEventHandlerWithAsyncData._loadDataFn (/usr/src/app/dist/src/plugins/email/handlers.js:25:56)
  at EmailEventHandlerWithAsyncData.handle (/usr/src/app/node_modules/@vendure/email-plugin/lib/src/handler/event-handler.js:299:41)
  at EmailPlugin.handleEvent (/usr/src/app/node_modules/@vendure/email-plugin/lib/src/plugin.js:354:42)
  at Object.next (/usr/src/app/node_modules/@vendure/email-plugin/lib/src/plugin.js:345:29)
  at ConsumerObserver.next (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33)
  at Subscriber._next (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:26)
  at Subscriber.next (/usr/src/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18) 
```

**To Reproduce**
1. Complete an order
2. Make sure you send an automated confirmation email
3. Watch your logs

**Expected behavior**
It should send out the confirmation email and not throw the above error. 

**Environment (please complete the following information):**
 - @vendure/core version: `2.2.4`
 - Nodejs version: `v20.14.0`
 - Database (mysql/postgres etc): postgres

**Additional context**
Probably related to #1931, though, not in the mailbox sandbox. In the /mailbox sandbox it works fine!

**Comment by michaelbromley** [comment]
Thanks for the report. I think this is occurring because when the RequestContext object is created [here](https://github.com/vendure-ecommerce/vendure/blob/cc4826dfb7c1a2f4e6ed8daa13eb017090d8bd9a/packages/payments-plugin/src/mollie/mollie.controller.ts#L39), there is no `request` object associated with it. 

We should be able to get the request object from the webhook method handler and pass it in. That should solve it.

**Comment by casperiv0** [comment]
Thanks @michaelbromley for the quick bug fix!
