### ISSUE TITLE
Admin UI: Metrics widget doesn't show numbers on hover: `Invalid language tag: en-`

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#2896]
**Describe the bug**

**To Reproduce**
1. Go to the dashboard in Brave
2. Hover over the chart to view actual numbers. Numbers are not showing
4. See error in console:
```js
RangeError: Invalid language tag: en-
    at new DateTimeFormat (<anonymous>)
    at vendure-admin-ui-core.mjs:19285:35
    at k.addEventListener.passive (vendure-admin-ui-core.mjs:19270:21)
    at H.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (core.mjs:11070:33)
    at H.invokeTask (zone.js:401:60)
    at k.runTask (zone.js:173:47)
    at Z.invokeTask [as invoke] (zone.js:483:34)
    at q (zone.js:1631:18)
    at tt (zone.js:1662:29)
```

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.5
 - Nodejs version 18
 - Database (mysql/postgres etc): MySQL
 - Browser: Brave

**Additional context**

**Comment by michaelbromley** [comment]
From the error message, it appears that the error originates [on this line](https://github.com/vendure-ecommerce/vendure/blob/fa7959065616c03ca786b1a15f8620d03f7a29bb/packages/admin-ui/src/lib/dashboard/src/widgets/order-chart-widget/order-chart-widget.component.ts#L61)

```ts
const locale = `${uiState.language}-${uiState.locale}`;
```

and `uiState.locale` has not been explicitly set, and also no "defaultLocale" is specified in the `vendure-ui-config.json` file, so is using the default value of `''`.

In fact, I'm not even sure how you get into this state under normal usage, because even if no "defaultLocale" is set, then the Admin UI _should_ take the locale from the browser: https://github.com/vendure-ecommerce/vendure/blob/b5cdbce5816697d3961c4caf66ce4d10cc8a4fe4/packages/admin-ui/src/lib/core/src/common/utilities/get-default-ui-language.ts#L13

Can you provide any more context around how to reproduce this? I'm unable to.

**Comment by martijnvdbrug** [comment]
@michaelbromley I am using Brave browser, but without the built-in blocker (disabled it for the Vendure admin). This issue occurs on all my client's dashboards, without doing anything weird:
1. Open /admin
2. Login
3. Hover the metrics chart
4. No numbers are shown on hover and the above error is shown in the browser logs
(Also just verified on V2.2.6)

**Comment by martijnvdbrug** [comment]
So, prints out `en` for `navigator.language`, so `navigator.language.split('-')[1]?.toUpperCase();` yeidls undefined in Brave. Not sure why this is the case...

![image](https://github.com/user-attachments/assets/74429ce8-0cc6-4b42-8ae7-9f957b9d74ff)

**Comment by martijnvdbrug** [comment]
Although this might not be expected output, it is valid according to its specs:

* `navigator.language` should give a valid [RFC5646](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language) language
* [This online rfc5646 validator](https://codsen.com/os/is-language-code/play) tells me that `en` is a valid language tag

**Comment by martijnvdbrug** [comment]
I am going to close this, as it is very specific to Brave and my personal settings. If anyone encounters this issue, change your first language in Brave settings to `English (United States)` instead of English.

![image](https://github.com/user-attachments/assets/5c536e5a-3c33-40e7-9d3e-298bb38ce839)
