### ISSUE TITLE
Allow developer to inject scripts into Admin UI's index.html (E.g in case an API needs it to work).

### ISSUE THREAD

**Issue by KariNarhi28** [vendure-ecommerce/vendure#3013]
**Is your feature request related to a problem? Please describe.**
Some API's, like Google Maps Javascript API, need to be loaded with script tags that are in index.html, but we don't have access to the Admin UI's index.html. 

**Describe the solution you'd like**
UiExtensionCompilerOptions should have property that allows inserting scripts into the index.html.

Pseudo-example:

```typescript
export const adminUIExtensionConfig: UiExtensionCompilerOptions = {
..., // All other config options
customScripts: CustomScript[] // Array of custom script config objects
}

interface CustomScript {
// Optional name of the script, used for e.g. debugging purposes
name?: string;
// Path to the script file
path: string;
// Type of the script file, could be a HTML-file with <script> tag 
// or Typescript/Javascript-file containing the script code.
type: 'html' | 'ts' | 'js'
}
```

**Describe alternatives you've considered**
Expose the Admin UI source to be able to configure all the parts without injecting through plugins.

E.g

When creating a Vendure project with `npx vendure create`, the CLI scaffolding process should create an admin-ui -folder which would include the source as it is (the whole Angular-project) and that folder should be included when compiling the Admin UI for development and production.

**Additional context**
Currently trying to create a plugin which allows to select a location for Product, using Google Maps Javascript API, but getting the error:

```shell
Error: Namespace google not found, cannot construct embedded google map.
Please install the Google Maps JavaScript API: https://developers.google.com/maps/documentation/javascript/tutorial#Loading_the_Maps_API
    at new GoogleMap (google-maps.mjs:208:23)
    at NodeInjectorFactory.GoogleMap_Factory [as factory] (google-maps.mjs:450:23)
    at getNodeInjectable (core.mjs:5984:44)
    at instantiateAllDirectives (core.mjs:11907:27)
    at createDirectivesInstances (core.mjs:11306:5)
    at Module.ɵɵelementStart (core.mjs:23045:9)
    at GoogleMapInputComponent_Template (google-map-input.component.html:45:1)
    at executeTemplate (core.mjs:11268:9)
    at renderView (core.mjs:12470:13)
    at renderComponent (core.mjs:12416:5)
```
Related Discord-thread here:
https://discord.com/channels/1100672177260478564/1273267093516582986

**Comment by dlhck** [comment]
I think it would also be possible to introduce a new helper function for the plugin Admin UI providers - something like `addExternalScript(src)`. This automatically picks up that script and injects it in the Admin UI. We could also introduce certain conditions (e.g. just load it in certain routes) and different loading strategies / orders (e.g. lazy loading)

**Comment by dlhck** [comment]
Could be done together with #2903

**Comment by dlhck** [comment]
This feature request has been moved to GitHub Discussions for community voting.
Please upvote the discussion if you would like to see this implemented: https://github.com/vendurehq/vendure/discussions/4250
