### ISSUE TITLE
Unable to upload assets via admin ui with Node 13.7 

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#458]
**Describe the bug**
When running Node 13.7, uploading assets via the Admin UI results in a `RangeError: Maximum call stack size exceeded`

**To Reproduce**
1. Start vendure as local devserver
2. Go to the Admin UI
3. Go to assets
4. Click 'Upload assets'
5. Select an image from your filesystem.

**Expected behavior**
The image is uploaded and added to the assets overview.

**Environment (please complete the following information):**
 - @vendure/core version: 0.15.0
 - Nodejs version 13.7.0
 - Database: sqlite

**Additional context**
```[run:server] RangeError: Maximum call stack size exceeded
[run:server]     at _openReadFs (internal/fs/streams.js:151:21)
[run:server]     at ReadStream.<anonymous> (internal/fs/streams.js:147:3)
[run:server]     at ReadStream.deprecated [as open] (internal/util.js:89:15)
[run:server]     at ReadStream.open (/home/git/vendure/node_modules/fs-capacitor/lib/index.js:90:11)
[run:server]     at _openReadFs (internal/fs/streams.js:154:12)
[run:server]     at ReadStream.<anonymous> (internal/fs/streams.js:147:3)
[run:server]     at ReadStream.deprecated [as open] (internal/util.js:89:15)
[run:server]     at ReadStream.open (/home/git/vendure/node_modules/fs-capacitor/lib/index.js:90:11)
[run:server]     at _openReadFs (internal/fs/streams.js:154:12)
[run:server]     at ReadStream.<anonymous> (internal/fs/streams.js:147:3)
```

**Comment by martijnvdbrug** [comment]
Suggested solution is to use `yarn` and add the following resolutions to your package.json:
```  "resolutions": {
    "**/**/fs-capacitor":"^5.0.0",
    "**/graphql-upload": "^9.0.0"
  }```

This will only work with `yarn`. If you're using `npm` you need to install https://github.com/rogeriochaves/npm-force-resolutions
OR just use node 12.
