### ISSUE TITLE
Cant upload image using the Admin UI

### ISSUE THREAD

**Issue by rohanrajpal** [vendure-ecommerce/vendure#582]
**Describe the bug**
I tried uploading a png file to the assets in the admin UI and I got the error ` Could not connect to the Vendure server at auto:auto`
Vendure is not usable after this error and I have to restart vendure.
**To Reproduce**
1. Go to admin UI `http://localhost:4000/admin/catalog/assets`
2. Click on Upload Asset
3. Select a png file

**Expected behavior**
I expect the file to be uploaded and am able to use it in my products

**Environment (please complete the following information):**
 - @vendure/core version:0.17.1
 - Nodejs version: v14.15.0
 - Database (mysql/postgres etc): Postgres

**Additional context**
Error in the admin UI
![image](https://user-images.githubusercontent.com/7023147/101394410-7cacbf80-38ee-11eb-8ae7-adba2a781b36.png)

Here is the error log

```
[I] ⋊> ~/D/G/s/server yarn start                                                    (base) 00:42:19
yarn run v1.22.5
$ concurrently yarn:run:*
$ ts-node ./src/index.ts
$ ts-node ./src/index-worker.ts
[run:server] info 08/12/20, 00:42 - [Vendure Server] Bootstrapping Vendure Server (pid: 97481)... 
[run:worker] info 08/12/20, 00:42 - [Vendure Worker] Bootstrapping Vendure Worker (pid: 97488)... 
[run:worker] info 08/12/20, 00:42 - [NestMicroservice] Nest microservice successfully started 
[run:worker] info 08/12/20, 00:42 - [Vendure Worker] Vendure Worker started with TCP transport at localhost:3020 
[run:server] info 08/12/20, 00:42 - [RoutesResolver] HealthController {/health}: 
[run:server] info 08/12/20, 00:42 - [RouterExplorer] Mapped {/health, GET} route 
[run:server] info 08/12/20, 00:42 - [AssetServerPlugin] Asset server listening on "http://localhost:3001" 
[run:server] info 08/12/20, 00:42 - [NestApplication] Nest application successfully started 
[run:server] info 08/12/20, 00:42 - [Vendure Server] ===================================================================== 
[run:server] info 08/12/20, 00:42 - [Vendure Server]           Vendure server (v0.17.1) now running on port 4000 
[run:server] info 08/12/20, 00:42 - [Vendure Server] --------------------------------------------------------------------- 
[run:server] info 08/12/20, 00:42 - [Vendure Server] Shop API:     http://localhost:4000/shop-api 
[run:server] info 08/12/20, 00:42 - [Vendure Server] Admin API:    http://localhost:4000/admin-api 
[run:server] info 08/12/20, 00:42 - [Vendure Server] Asset Server: http://localhost:4000/assets/ -> http://localhost:3001 
[run:server] info 08/12/20, 00:42 - [Vendure Server] Dev Mailbox:  http://localhost:4000/mailbox/ -> http://localhost:3003 
[run:server] info 08/12/20, 00:42 - [Vendure Server] Admin UI:     http://localhost:4000/admin/ -> http://localhost:3002 
[run:server] info 08/12/20, 00:42 - [Vendure Server] ===================================================================== 
[run:server] warn 08/12/20, 00:43 - [Vendure Server] FORBIDDEN: error.forbidden 
[run:server] warn 08/12/20, 00:43 - [Vendure Server] FORBIDDEN: error.forbidden 
[run:server] warn 08/12/20, 00:43 - [Vendure Server] FORBIDDEN: error.forbidden 
[run:server] RangeError: Maximum call stack size exceeded
[run:server]     at ReadStream.deprecated [as open] (internal/util.js:74:22)
[run:server]     at ReadStream.open (/home/rohan/Documents/Github/sevashop/server/node_modules/fs-capacitor/lib/index.js:90:11)
[run:server]     at _openReadFs (internal/fs/streams.js:138:12)
[run:server]     at ReadStream.<anonymous> (internal/fs/streams.js:131:3)
[run:server]     at ReadStream.deprecated [as open] (internal/util.js:89:15)
[run:server]     at ReadStream.open (/home/rohan/Documents/Github/sevashop/server/node_modules/fs-capacitor/lib/index.js:90:11)
[run:server]     at _openReadFs (internal/fs/streams.js:138:12)
[run:server]     at ReadStream.<anonymous> (internal/fs/streams.js:131:3)
[run:server]     at ReadStream.deprecated [as open] (internal/util.js:89:15)
[run:server]     at ReadStream.open (/home/rohan/Documents/Github/sevashop/server/node_modules/fs-capacitor/lib/index.js:90:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[run:server] yarn run run:server exited wi
```

**Comment by michaelbromley** [comment]
This looks like this issue: https://github.com/vendure-ecommerce/vendure/issues/396

Short answer: downgrade to Node v12.x for now.

**Comment by rohanrajpal** [comment]
> This looks like this issue: #396
> 
> Short answer: downgrade to Node v12.x for now.

Thanks, my bad, I did try to search for a similar issue but must have missed this.
