### ISSUE TITLE
v0.18.0 - column "handlerCode" contains null values

### ISSUE THREAD

**Issue by matigastirami** [vendure-ecommerce/vendure#621]
I'm getting the following error when I try to start the server:

```
error 21-1-6 10:35 - [TypeOrmModule] Unable to connect to the database. Retrying (5)...
QueryFailedError: column "handlerCode" contains null values
    at new QueryFailedError (C:\Workspace\Mobbex\ecommerce-service\node_modules\typeorm\error\QueryFailedError.js:11:28)
    at Query.callback (C:\Workspace\Mobbex\ecommerce-service\node_modules\typeorm\driver\postgres\PostgresQueryRunner.js:187:38)
    at Query.handleError (C:\Workspace\Mobbex\ecommerce-service\node_modules\pg\lib\query.js:128:19)
    at Client._handleErrorMessage (C:\Workspace\Mobbex\ecommerce-service\node_modules\pg\lib\client.js:335:17)
    at Connection.emit (events.js:315:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at C:\Workspace\Mobbex\ecommerce-service\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (C:\Workspace\Mobbex\ecommerce-service\node_modules\pg-protocol\dist\parser.js:40:17)
    at Socket.<anonymous> (C:\Workspace\Mobbex\ecommerce-service\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:315:20)
```

It started to happen yesterday when I updated from v0.17.3 to v0.18.0. I try to solve it creating a new column manually on table shipping-method. I also created a fulfillmentHandler but the error didn't disappear.

**Comment by michaelbromley** [comment]
Hi, did you follow the migration instructions given here: https://www.vendure.io/blog/2020/12/announcing-vendure-v0.18.0/#breaking-changes--migration-guide ?

**Comment by matigastirami** [comment]
Hello! I hadn't read it, sorry. I had to drop all the database tables and then it started to work (I'm not in production yet). Thanks Michael!
