### ISSUE TITLE
Cannot start Server

### ISSUE THREAD

**Issue by kamalkech** [vendure-ecommerce/vendure#925]
**Environment (please complete the following information):**
 - @vendure/core version: 1.0.1
 - Nodejs v12.22.0
 - Database (mysql/postgres etc): sqlite / postgres

when try to start server i get this error:

```
yarn run v1.22.10
$ concurrently yarn:run:*
$ ts-node ./src/index-worker.ts
$ ts-node ./src/index.ts
[run:worker] 
[run:worker] /mnt/1C12BBAC12BB8972/Projects/Vendure/formation/node_modules/juice/node_modules/cheerio/lib/api/traversing.js:130
[run:worker]     }).apply(void 0, tslib_1.__spreadArray([nextElem], postFns));
[run:worker]                              ^
[run:worker] TypeError: tslib_1.__spreadArray is not a function
[run:worker]     at _matchUntil (/mnt/1C12BBAC12BB8972/Projects/Vendure/formation/node_modules/juice/node_modules/cheerio/lib/api/traversing.js:130:30)
[run:worker]     at Object.<anonymous> (/mnt/1C12BBAC12BB8972/Projects/Vendure/formation/node_modules/juice/node_modules/cheerio/lib/api/traversing.js:212:24)
[run:worker]     at Module._compile (internal/modules/cjs/loader.js:999:30)
[run:worker]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[run:worker]     at Module.load (internal/modules/cjs/loader.js:863:32)
[run:worker]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[run:worker]     at Module.require (internal/modules/cjs/loader.js:887:19)
[run:worker]     at require (internal/modules/cjs/helpers.js:74:18)
[run:worker]     at Object.<anonymous> (/mnt/1C12BBAC12BB8972/Projects/Vendure/formation/node_modules/juice/node_modules/cheerio/lib/cheerio.js:9:39)
[run:worker]     at Module._compile (internal/modules/cjs/loader.js:999:30)
[run:server] 
[run:server] /mnt/1C12BBAC12BB8972/Projects/Vendure/formation/node_modules/juice/node_modules/cheerio/lib/api/traversing.js:130
[run:server]     }).apply(void 0, tslib_1.__spreadArray([nextElem], postFns));
[run:server]                              ^
[run:server] TypeError: tslib_1.__spreadArray is not a function
[run:server]     at _matchUntil (/mnt/1C12BBAC12BB8972/Projects/Vendure/formation/node_modules/juice/node_modules/cheerio/lib/api/traversing.js:130:30)
[run:server]     at Object.<anonymous> (/mnt/1C12BBAC12BB8972/Projects/Vendure/formation/node_modules/juice/node_modules/cheerio/lib/api/traversing.js:212:24)
[run:server]     at Module._compile (internal/modules/cjs/loader.js:999:30)
[run:server]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[run:server]     at Module.load (internal/modules/cjs/loader.js:863:32)
[run:server]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[run:server]     at Module.require (internal/modules/cjs/loader.js:887:19)
[run:server]     at require (internal/modules/cjs/helpers.js:74:18)
[run:server]     at Object.<anonymous> (/mnt/1C12BBAC12BB8972/Projects/Vendure/formation/node_modules/juice/node_modules/cheerio/lib/cheerio.js:9:39)
[run:server]     at Module._compile (internal/modules/cjs/loader.js:999:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[run:worker] yarn run run:worker exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[run:server] yarn run run:server exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by michaelbromley** [comment]
Thanks for the report. Looks like some issue with a dependency, maybe something just got updated in the past day or so. I'll investigate.

**Comment by michaelbromley** [comment]
Looks like a change with a deep dependency:

```
@vendure.email-plugin -> mjml ^4.7.1
mjml -> mjml-core 4.9.3
mjml-core -> juice ^7.0.0
juice -> cheerio ^1.0.0-rc.3 (resolving to 1.0.0-rc.10 which was released 2 days ago)
```

The cheerio release looks to be the change that broke things. Adding the `tslib` package fixes it. I will add that dependency to the `@vendure/create` package.

**Comment by michaelbromley** [comment]
On further investigation the real villain is me: 

https://github.com/vendure-ecommerce/vendure/blob/1e8c1375f7e6ff8f80b90ac1cd40e9c4a53ae1bf/packages/create/src/create-vendure-app.ts#L109-L117

Removing this line will allow correct tslib resolutions in deep dependencies.

**Comment by kamalkech** [comment]
@michaelbromley so merged in package code now ??

**Comment by michaelbromley** [comment]
yes, try with v1.0.2

**Comment by kamalkech** [comment]
i will check right now

**Comment by kamalkech** [comment]
good work fine know, this is my first test and i see using angular + nextjs that s bizard, finnaly thank u for ur feedback and plz share discord channel

**Comment by michaelbromley** [comment]
Glad to head it is working for you now. There is no discord channel, we are currently using slack for chat: https://join.slack.com/t/vendure-ecommerce/shared_invite/enQtNzA1NTcyMDY3NTg0LTMzZGQzNDczOWJiMTU2YjAyNWJlMzdmZGE3ZDY5Y2RjMGYxZWNlYTI4NmU4Y2Q1MDNlYzE4MzQ5ODcyYTdmMGU
