### ISSUE TITLE
Server crashing when attempting to upload very large asset

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/vendure#990]
**Describe the bug**
When attempting to upload a very large file via the `createAssets` mutation of the Admin API, an error is thrown on the server and the server process exits(!!)

**To Reproduce**
1. In the admin ui go to the assets list and attempt to upload a big file, e.g. 200MB video
2. See the following error in the server console:

```
[run:server] C:\Development\vendure\vendure\node_modules\graphql-upload\public\processRequest.js:289
[run:server]         fileError = createError(
[run:server]                     ^
[run:server] PayloadTooLargeError: File truncated as it exceeds the 20971520 byte size limit.
[run:server]     at FileStream.<anonymous> (C:\Development\vendure\vendure\node_modules\graphql-upload\public\processRequest.js:289:21)
[run:server]     at FileStream.emit (node:events:365:28)
[run:server]     at FileStream.emit (node:domain:470:12)
[run:server]     at PartStream.onData (C:\Development\vendure\vendure\node_modules\busboy\lib\types\multipart.js:221:18)
[run:server]     at PartStream.emit (node:events:365:28)
[run:server]     at PartStream.emit (node:domain:470:12)
[run:server]     at addChunk (node:internal/streams/readable:314:12)
[run:server]     at readableAddChunk (node:internal/streams/readable:289:9)
[run:server]     at PartStream.Readable.push (node:internal/streams/readable:228:10)
[run:server]     at Dicer._oninfo (C:\Development\vendure\vendure\node_modules\dicer\lib\Dicer.js:190:36)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
[run:server] yarn run run:server exited with code 1
```

**Expected behavior**
Just a regular GraphQL error response. No dead server!

**Environment (please complete the following information):**
 - @vendure/core version: 1.1.0
 - Nodejs version: 16.x
 - Database (mysql/postgres etc): any

**Comment by michaelbromley** [comment]
Looks like the cause is this issue: https://github.com/jaydenseric/graphql-upload/issues/45

Investigating remedies...
